apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spilo
  labels:
    release: prometheus
    application: spilo
spec:
  selector:
    matchLabels:
      application: spilo

  podMetricsEndpoints:
  # Patroni
  - portNumber: 8008
    relabelings:
      - sourceLabels: [__meta_kubernetes_pod_label_cluster_name]
        targetLabel: service

  # Posgtgres exporter
  - port: exporter
    relabelings:
      - sourceLabels: [__meta_kubernetes_pod_label_cluster_name]
        targetLabel: service

  # WALG exporter
  - port: backup-exporter
    relabelings:
      - sourceLabels: [__meta_kubernetes_pod_label_cluster_name]
        targetLabel: service
