apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cert-manager
  name: cert-manager
spec:
  template:
    spec:
      priorityClassName: critical-operator
      containers:
        - name: cert-manager-controller
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 48Mi
