apiVersion: batch/v1
kind: Job
metadata:
  name: splitting-phase-2-job
  labels:
    app.kubernetes.io/component: shard-splitting-job
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: shard-splitting-job
    spec:
      serviceAccountName: shard-splitter
      podReplacementPolicy: Failed
      priorityClassName: shard-background-worker
      imagePullSecrets:
        - name: regcreds
      containers:
      - name: prepare-for-running-new-shards
        image: swpt-split-shard
        args: ['prepare-for-running-new-shards']
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        envFrom:
          - secretRef:
              name: db-owner-credentials
            prefix: pg_
          - configMapRef:
              name: git-ops-config
          - configMapRef:
              name: splitting-jobs-config
        env:
          - name: WORKING_DIRECTORY
            value: "/mnt/git-ops"
        resources:
          requests:
            cpu: 50m
            memory: 200Mi
            ephemeral-storage: 1Gi
          limits:
            cpu: "1"
            memory: 300Mi
            ephemeral-storage: 5Gi
        volumeMounts:
          - mountPath: "/mnt/git-ops/"
            name: git-repo-working-copy
            readOnly: false
          - name: git-ops-ssh-id
            mountPath: "/etc/ssh/id_rsa"
            subPath: id_rsa
          - name: git-ops-ssh-id
            mountPath: "/etc/ssh/id_rsa.pub"
            subPath: id_rsa.pub
          - name: git-ops-ssh-id
            mountPath: "/etc/ssh/id_rsa-cert.pub"
            subPath: id_rsa-cert.pub
      initContainers:
      - name: wait-for-pods-termination
        image: swpt-split-shard
        args: ['wait-for-pods-termination']
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        envFrom:
          - configMapRef:
              name: splitting-jobs-config
        env:
          - name: APP_K8S_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 50m
            memory: 200Mi
          limits:
            cpu: "1"
            memory: 300Mi
      - name: subscribe-0
        image: swpt-creditors
        args: ['subscribe']
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        envFrom:
          - secretRef:
              name: db-owner-credentials
            prefix: pg_
          - secretRef:
              name: broker-default-user
            prefix: rmq_
          - configMapRef:
              name: splitting-jobs-config
        env:
          - name: POSTGRES_URL
            value: "postgresql+psycopg://$(pg_username):$(pg_password)@$(SHARDS_PG_CLUSTER_PREFIX)$(SHARD0_SUFFIX):5432/db"
          - name: PROTOCOL_BROKER_URL
            value: "$(rmq_connection_string)"
          - name: PROTOCOL_BROKER_QUEUE
            value: "$(SHARDS_PG_CLUSTER_PREFIX)$(SHARD0_SUFFIX)"
          - name: PROTOCOL_BROKER_QUEUE_ROUTING_KEY
            value: "$(SHARD0_ROUTING_KEY)"
          - name: APP_LOG_LEVEL
            value: info
        resources:
          requests:
            cpu: 50m
            memory: 200Mi
          limits:
            cpu: "1"
            memory: 300Mi
      - name: subscribe-1
        image: swpt-creditors
        args: ['subscribe']
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        envFrom:
          - secretRef:
              name: db-owner-credentials
            prefix: pg_
          - secretRef:
              name: broker-default-user
            prefix: rmq_
          - configMapRef:
              name: splitting-jobs-config
        env:
          - name: POSTGRES_URL
            value: "postgresql+psycopg://$(pg_username):$(pg_password)@$(SHARDS_PG_CLUSTER_PREFIX)$(SHARD1_SUFFIX):5432/db"
          - name: PROTOCOL_BROKER_URL
            value: "$(rmq_connection_string)"
          - name: PROTOCOL_BROKER_QUEUE
            value: "$(SHARDS_PG_CLUSTER_PREFIX)$(SHARD1_SUFFIX)"
          - name: PROTOCOL_BROKER_QUEUE_ROUTING_KEY
            value: "$(SHARD1_ROUTING_KEY)"
          - name: APP_LOG_LEVEL
            value: info
        resources:
          requests:
            cpu: 50m
            memory: 200Mi
          limits:
            cpu: "1"
            memory: 300Mi
      - name: unsubscribe
        image: swpt-creditors
        args: ['unsubscribe']
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        envFrom:
          - secretRef:
              name: db-owner-credentials
            prefix: pg_
          - secretRef:
              name: broker-default-user
            prefix: rmq_
          - configMapRef:
              name: splitting-jobs-config
        env:
          - name: POSTGRES_URL
            value: "postgresql+psycopg://$(pg_username):$(pg_password)@$(SHARDS_PG_CLUSTER_PREFIX)$(SHARD_SUFFIX):5432/db"
          - name: PROTOCOL_BROKER_URL
            value: "$(rmq_connection_string)"
          - name: PROTOCOL_BROKER_QUEUE
            value: "$(SHARDS_PG_CLUSTER_PREFIX)$(SHARD_SUFFIX)"
          - name: PROTOCOL_BROKER_QUEUE_ROUTING_KEY
            value: "$(SHARD_ROUTING_KEY)"
          - name: APP_LOG_LEVEL
            value: info
        resources:
          requests:
            cpu: 50m
            memory: 200Mi
          limits:
            cpu: "1"
            memory: 300Mi
      - name: delete-queue
        image: swpt-creditors
        args: ['delete_queue']
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        envFrom:
          - secretRef:
              name: db-owner-credentials
            prefix: pg_
          - secretRef:
              name: broker-default-user
            prefix: rmq_
          - configMapRef:
              name: splitting-jobs-config
        env:
          - name: POSTGRES_URL
            value: "postgresql+psycopg://$(pg_username):$(pg_password)@$(SHARDS_PG_CLUSTER_PREFIX)$(SHARD_SUFFIX):5432/db"
          - name: PROTOCOL_BROKER_URL
            value: "$(rmq_connection_string)"
          - name: PROTOCOL_BROKER_QUEUE
            value: "$(SHARDS_PG_CLUSTER_PREFIX)$(SHARD_SUFFIX)"
          - name: PROTOCOL_BROKER_QUEUE_ROUTING_KEY
            value: "$(SHARD_ROUTING_KEY)"
          - name: APP_LOG_LEVEL
            value: info
        resources:
          requests:
            cpu: 50m
            memory: 200Mi
          limits:
            cpu: "1"
            memory: 300Mi
      restartPolicy: OnFailure
      volumes:
        - name: git-repo-working-copy
          emptyDir: {}
        - name: git-ops-ssh-id
          secret:
            secretName: git-ops-ssh-id
            defaultMode: 0600
  backoffLimit: 2147483647
