apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: broker
spec:
  replicas: 1
  rabbitmq:
    additionalPlugins:
      - rabbitmq_random_exchange
      - rabbitmq_management
  persistence:
    storage: 1300Mi
  resources:
    requests:
      cpu: 100m
      memory: 700Mi
    limits:
      cpu: 1000m
      memory: 700Mi
