#
# Patches for the "nfs-server" container:
#
- op: test
  path: /spec/template/spec/containers/0/name
  value: nfs-server

- op: replace
  path: /spec/template/spec/containers/0/resources
  value:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 64Mi


#
# Patches for the "git-pull" container:
#
- op: test
  path: /spec/template/spec/containers/1/name
  value: git-pull

- op: replace
  path: /spec/template/spec/containers/1/resources
  value:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 64Mi
