source:
  kind: ConfigMap
  name: creditors-agent-config
  fieldPath: metadata.annotations.kustomize_swagger_ui_cpu_limit
targets:
  - select:
      kind: Deployment
      name: swagger-ui
    fieldPaths:
      - spec.template.spec.containers.[name=swagger-ui].resources.limits.cpu
    options:
      create: true

