apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  labels:
    app.kubernetes.io/component: web-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: web-server
  template:
    metadata:
      labels:
        app.kubernetes.io/component: web-server
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          minDomains: 2
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: web-server
      containers:
        - name: web-server
          image: swpt-accounts
          args: ['webserver']
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - secretRef:
                name: db-owner-credentials
              prefix: pg_
            - secretRef:
                name: broker-default-user
              prefix: rmq_
            - configMapRef:
                name: shardconfig
          env:
            - name: WEBSERVER_PORT
              value: "8080"
            - name: POSTGRES_URL
              value: "postgresql+psycopg://$(pg_username):$(pg_password)@$(pg_cluster_name).swpt-accounts.svc:5432/db"
            - name: PROTOCOL_BROKER_URL
              value: "$(rmq_connection_string)"
            - name: PROTOCOL_BROKER_QUEUE
              value: "$(pg_cluster_name)"
            - name: CHORES_BROKER_URL
              value: "$(rmq_connection_string)"
            - name: CHORES_BROKER_QUEUE
              value: "$(pg_cluster_name)-chores"
