apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web-server-pdb
  labels:
    app.kubernetes.io/component: web-server
spec:
  maxUnavailable: 30%
  selector:
    matchLabels:
      app.kubernetes.io/component: web-server
