apiVersion: v1
kind: Service
metadata:
  name: web-server
spec:
  selector:
    app.kubernetes.io/component: web-server
  ports:
    - name: http
      port: 80
      protocol: TCP
      appProtocol: http
      targetPort: 80
  type: LoadBalancer
