---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers
  prune: true
  wait: true

  # OCI images to use for the different containers:
  #
  images:
  - name: ghcr.io/zalando/postgres-operator:v1.14.0
    newName: ghcr.io/zalando/postgres-operator
    newTag: v1.14.0
  - name: quay.io/brancz/kube-rbac-proxy:v0.16.0
    newName: quay.io/brancz/kube-rbac-proxy
    newTag: v0.16.0
  - name: docker.dragonflydb.io/dragonflydb/operator:v1.1.11
    newName: docker.dragonflydb.io/dragonflydb/operator
    newTag: v1.1.11
  - name: quay.io/jetstack/cert-manager-cainjector:v1.17.2
    newName: quay.io/jetstack/cert-manager-cainjector
    newTag: v1.17.2
  - name: quay.io/jetstack/cert-manager-controller:v1.17.2
    newName: quay.io/jetstack/cert-manager-controller
    newTag: v1.17.2
  - name: quay.io/jetstack/cert-manager-webhook:v1.17.2
    newName: quay.io/jetstack/cert-manager-webhook
    newTag: v1.17.2
  - name: rabbitmqoperator/cluster-operator:2.12.1
    newName: rabbitmqoperator/cluster-operator
    newTag: 2.12.1
  - name: rabbitmqoperator/messaging-topology-operator:1.17.0
    newName: rabbitmqoperator/messaging-topology-operator
    newTag: 1.17.0

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  dependsOn:
    - name: infra-controllers
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/configs
  prune: true
