####################################################################
# This file is needed only if "mailhog" is used as mail server for #
# testing.                                                         #
####################################################################

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mailhog
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./testing-tools/mailhog
  prune: true
  timeout: 5m0s
