####################################################################
# This file is needed only if "pebble" is used as ACME certificate #
# provider for testing.                                            #
####################################################################

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pebble
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./testing-tools/pebble
  prune: true
  timeout: 5m0s
