apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/name: swpt-debtors

secretGenerator:
- name: postgres.login-db.credentials.postgresql.acid.zalan.do
  files:
  - password=../secrets/postgres-cluster-password.encrypted
  literals:
  - username=postgres
  options:
    disableNameSuffixHash: true
    labels:
      application: spilo
      cluster-name: login-db
      team: swpt
  type: Opaque
- name: standby.login-db.credentials.postgresql.acid.zalan.do
  files:
  - password=../secrets/postgres-cluster-password.encrypted
  literals:
  - username=standby
  options:
    disableNameSuffixHash: true
    labels:
      application: spilo
      cluster-name: login-db
      team: swpt
  type: Opaque
- name: db-owner.login-db.credentials.postgresql.acid.zalan.do
  files:
  - password=../secrets/postgres-cluster-password.encrypted
  literals:
  - username=db_owner
  options:
    disableNameSuffixHash: true
    labels:
      application: spilo
      cluster-name: login-db
      team: swpt
  type: Opaque

resources:
- postgres-cluster.yaml
- ../../../base/swpt-debtors/login-db/network-policies.yaml

patches:
- path: ../../../base/swpt-debtors/login-db/patches/postgres-cluster.yaml
  target:
    group: acid.zalan.do
    kind: postgresql
    name: login-db
    version: v1
