apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    application: spilo
    cluster-name: accounts-db
    team: swpt

secretGenerator:
  - name: postgres.accounts-db.credentials.postgresql.acid.zalan.do
    literals:
      - username=postgres
    files:
      - password=postgres-cluster-password.encrypted
    type: Opaque
  - name: standby.accounts-db.credentials.postgresql.acid.zalan.do
    literals:
      - username=standby
    files:
      - password=postgres-cluster-password.encrypted
    type: Opaque
  - name: db-owner.accounts-db.credentials.postgresql.acid.zalan.do
    literals:
      - username=db_owner
    files:
      - password=postgres-cluster-password.encrypted
    type: Opaque

resources:
  - manifests/

patches:
  - target:
      group: acid.zalan.do
      version: v1
      kind: postgresql
      name: accounts-db
    path: postgres-cluster-patch.yaml
