apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: postgres.shard.credentials.postgresql.acid.zalan.do
  literals:
    - username=postgres
    - password=gMF2r5GpFIEoLx2AJWDbunRd61TLIRaQrj5OKHQrM20jTBJnCOTpWNt4HrpmLlW2
  type: Opaque
  options:
    disableNameSuffixHash: true
    labels:
      application: spilo
      cluster-name: shard
      team: swpt
- name: standby.shard.credentials.postgresql.acid.zalan.do
  literals:
    - username=standby
    - password=5n1LczUVX4abuJjtWUWERlxjWR0G1lyOMN34b4yT3Yv4l07Ctm841CK2doxiP2xo
  type: Opaque
  options:
    disableNameSuffixHash: true
    labels:
      application: spilo
      cluster-name: shard
      team: swpt
- name: db-owner.shard.credentials.postgresql.acid.zalan.do
  literals:
    - username=db_owner
    - password=NRvDlAID3vbwGsCZqRt8WGIoaRuMFGko9x9rahyHQrsemnMPcUzxaHTJMMBOFUbs
  type: Opaque
  options:
    disableNameSuffixHash: true
    labels:
      application: spilo
      cluster-name: shard
      team: swpt

resources:
  - postgres-cluster.yaml

patches:
  - target:
      group: acid.zalan.do
      version: v1
      kind: postgresql
      name: shard
    path: patches/postgres-cluster-template.yaml
