apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-credentials.yaml
  - postgres-cluster.yaml

patches:
  - target:
      group: acid.zalan.do
      version: v1
      kind: postgresql
      name: accounts-db
    path: postgres-cluster-plumbing.yaml
