apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: swpt-accounts

secretGenerator:
  - name: postgres.accounts-db.credentials.postgresql.acid.zalan.do
    literals:
      - username=postgres
    files:
      - password=postgres-cluster-password.encrypted
    type: Opaque
    options:
      disableNameSuffixHash: true
      labels:
        application: spilo
        cluster-name: accounts-db
        team: swpt
  - name: standby.accounts-db.credentials.postgresql.acid.zalan.do
    literals:
      - username=standby
    files:
      - password=postgres-cluster-password.encrypted
    type: Opaque
    options:
      disableNameSuffixHash: true
      labels:
        application: spilo
        cluster-name: accounts-db
        team: swpt
  - name: db-owner.accounts-db.credentials.postgresql.acid.zalan.do
    literals:
      - username=db_owner
    files:
      - password=postgres-cluster-password.encrypted
    type: Opaque
    options:
      disableNameSuffixHash: true
      labels:
        application: spilo
        cluster-name: accounts-db
        team: swpt

resources:
  - postgres-cluster.yaml
  - shard-main.yaml

patches:
  - target:
      group: acid.zalan.do
      version: v1
      kind: postgresql
      name: accounts-db
    path: postgres-cluster-patch.yaml
