apiVersion: v1
kind: Secret
metadata:
    name: postgres.accounts-db.credentials.postgresql.acid.zalan.do
    labels:
        application: spilo
        cluster-name: accounts-db
        team: swpt
type: Opaque
data:
    username: ENC[AES256_GCM,data:+dTy46tsL7A=,iv:Q6j4irJRPDlxgpG7iItez2i427iaiV9HiBHTCbOE7ho=,tag:zBFtAiGfQISHVrAUtzJEiQ==,type:str]
    password: ENC[AES256_GCM,data:BITgf8S0do1YIQkKkaSFustu0JnJwB6meCvR2x54sr9RHPNSn8pbO2UAHhbSVHxNrlvOlbsfc13A/E+q7jomsQ==,iv:zIXZLK35xijeHayIznf4zHegSV/nqXFXpiogFJrE0GY=,tag:O4rLHqfbpfpUaMSnj3/vdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-08T17:51:33Z"
    mac: ENC[AES256_GCM,data:RqilSN8QCBiHguFaczFUPw00YILmsYVMnc2386NgZ3SCoDrTuDAhYUWzEfUxmf8spGqmfFaV0jj8WXKzV0u/gHy1WeTey4gFvVuAN+CFrrDEdlwpGeiV2V3akNKFSdLDiN0BhbjbomsY2nrPucIHMv4KZHxfiC4ZyXoUZrWXydY=,iv:zUkEtzd9bqVOJSkcSrMgcD1xvwTCypMt9jwwqViKEaE=,tag:4+iUGxOj+QHUphS848IUAQ==,type:str]
    pgp:
        - created_at: "2025-02-08T17:48:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA42dIjBdQ7obAQ//YWlTgNh2UprB/X+630QvYBuZE4NfopflHBeaIjh9qfcA
            W6/ojTLoZKeP3EcgQiC3JOwhp5gtLCVC1OpGiAXYEztQJckYf/wllHkykSXajvDj
            9OUfKQUbEqUwcuVJrseFSS+EP8BwT8oQgkvUXtQP5uK4cwETCLl8KTVdinpynaRp
            M8lgzD0W9chTRQJSyLDytHXUmqFmU1HkV1ZLXTFI3yit12nCOd2yhIm5MxxmqvbS
            e1YaMU2iGnWGL8xO0LcZhwxVjEu3dNIEFNYr2meEsN8BvK3x3JuKQGVCyJVt0tae
            +NNScQaASxghxAaWjlitpsuV4PhJYQQJAGy4TgtkKiEsh04b/6j0u5omnqSBNHFP
            tUKFCr25lnoG2+6r3EO6//xF6SZxF/yZHWjo5qLJ6XshuTpNRPBzqYMGWX/jFMQD
            ifQiQTD01UdN+4kg9HP/q+DKAxKI5ETrd5so/t2LQ3ya6UACmc/WXecMsnHy8waR
            2bjv0qI24d+31OSUQYMCaegkey96/DQRqYI1830jhxIZEq5X/GuCWplHO7xvHBIv
            LROOIyf/UmIbR8bvDiyIfoFP3Y8Docc87UFI/BKPDP6ql7I9RhjRmw6StXx9VhhX
            NsXxfI2lzqhk3bacMEmRr9MQ/QuHpBaKVjA8bdw+xzP6Fx1NGCU070RXJUl0L6LS
            XgHD31TRYQe1H/xI/ZOWAL4kWQd3VWs+N2SKSVYbOi4qGMOEN029q8VnK6B/Fnwo
            VBTGCvTLucaCwHtAfac6o8nCuHnZ8wT6VV13lnWu4n7BFoq0IbzwRpatLZa6Nqg=
            =buri
            -----END PGP MESSAGE-----
          fp: 2ED21ED3DBBF5A37898D9D316225432F3481C8E0
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: standby.accounts-db.credentials.postgresql.acid.zalan.do
    labels:
        application: spilo
        cluster-name: accounts-db
        team: swpt
type: Opaque
data:
    username: ENC[AES256_GCM,data:NTFnQQ02hw==,iv:KRN12HqoDszPUPG24nhdSF27vayU73m4rieU8MkjHOQ=,tag:rlyd9n+QIzRGRAZ3f21DRw==,type:str]
    password: ENC[AES256_GCM,data:wM+oRgrDBw26EJv0EKuoZGuAcZP7aphRMYb+8a16i5MZIVZ07L1I5/9KvIBp849NRvBSp5zLyjywEurC7exSew==,iv:Qc3mCI44GSjM6pDs5yLHJ5lb5EHZdmNhS6GU1qdK0nk=,tag:Bm2D9rQIOsPm8snj6vVvGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-08T17:51:33Z"
    mac: ENC[AES256_GCM,data:RqilSN8QCBiHguFaczFUPw00YILmsYVMnc2386NgZ3SCoDrTuDAhYUWzEfUxmf8spGqmfFaV0jj8WXKzV0u/gHy1WeTey4gFvVuAN+CFrrDEdlwpGeiV2V3akNKFSdLDiN0BhbjbomsY2nrPucIHMv4KZHxfiC4ZyXoUZrWXydY=,iv:zUkEtzd9bqVOJSkcSrMgcD1xvwTCypMt9jwwqViKEaE=,tag:4+iUGxOj+QHUphS848IUAQ==,type:str]
    pgp:
        - created_at: "2025-02-08T17:48:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA42dIjBdQ7obAQ//YWlTgNh2UprB/X+630QvYBuZE4NfopflHBeaIjh9qfcA
            W6/ojTLoZKeP3EcgQiC3JOwhp5gtLCVC1OpGiAXYEztQJckYf/wllHkykSXajvDj
            9OUfKQUbEqUwcuVJrseFSS+EP8BwT8oQgkvUXtQP5uK4cwETCLl8KTVdinpynaRp
            M8lgzD0W9chTRQJSyLDytHXUmqFmU1HkV1ZLXTFI3yit12nCOd2yhIm5MxxmqvbS
            e1YaMU2iGnWGL8xO0LcZhwxVjEu3dNIEFNYr2meEsN8BvK3x3JuKQGVCyJVt0tae
            +NNScQaASxghxAaWjlitpsuV4PhJYQQJAGy4TgtkKiEsh04b/6j0u5omnqSBNHFP
            tUKFCr25lnoG2+6r3EO6//xF6SZxF/yZHWjo5qLJ6XshuTpNRPBzqYMGWX/jFMQD
            ifQiQTD01UdN+4kg9HP/q+DKAxKI5ETrd5so/t2LQ3ya6UACmc/WXecMsnHy8waR
            2bjv0qI24d+31OSUQYMCaegkey96/DQRqYI1830jhxIZEq5X/GuCWplHO7xvHBIv
            LROOIyf/UmIbR8bvDiyIfoFP3Y8Docc87UFI/BKPDP6ql7I9RhjRmw6StXx9VhhX
            NsXxfI2lzqhk3bacMEmRr9MQ/QuHpBaKVjA8bdw+xzP6Fx1NGCU070RXJUl0L6LS
            XgHD31TRYQe1H/xI/ZOWAL4kWQd3VWs+N2SKSVYbOi4qGMOEN029q8VnK6B/Fnwo
            VBTGCvTLucaCwHtAfac6o8nCuHnZ8wT6VV13lnWu4n7BFoq0IbzwRpatLZa6Nqg=
            =buri
            -----END PGP MESSAGE-----
          fp: 2ED21ED3DBBF5A37898D9D316225432F3481C8E0
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: db-owner.accounts-db.credentials.postgresql.acid.zalan.do
    labels:
        application: spilo
        cluster-name: accounts-db
        team: swpt
type: Opaque
data:
    username: ENC[AES256_GCM,data:ME9lSGa+CLE=,iv:myFcf60jPONgTZ587Q8lJZpTNmWDIneoNracq4XLUVA=,tag:DKspkLhbsFRBDnz/VmfwSw==,type:str]
    password: ENC[AES256_GCM,data:JNV63eUj0akyM67eDWkNSXZw3aXrvWqfZcLVymOqcDcHSaqnXCe3IBTK75ILjvrkGZf2kxiJbtg8DgqSpJd4Sg==,iv:7vM+jckdw8RQks0DVTw9TcvI1U+26P0/aLEi27IuaMs=,tag:PTpaM3BVfpN5VQl5Kz3olA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-08T17:51:33Z"
    mac: ENC[AES256_GCM,data:RqilSN8QCBiHguFaczFUPw00YILmsYVMnc2386NgZ3SCoDrTuDAhYUWzEfUxmf8spGqmfFaV0jj8WXKzV0u/gHy1WeTey4gFvVuAN+CFrrDEdlwpGeiV2V3akNKFSdLDiN0BhbjbomsY2nrPucIHMv4KZHxfiC4ZyXoUZrWXydY=,iv:zUkEtzd9bqVOJSkcSrMgcD1xvwTCypMt9jwwqViKEaE=,tag:4+iUGxOj+QHUphS848IUAQ==,type:str]
    pgp:
        - created_at: "2025-02-08T17:48:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA42dIjBdQ7obAQ//YWlTgNh2UprB/X+630QvYBuZE4NfopflHBeaIjh9qfcA
            W6/ojTLoZKeP3EcgQiC3JOwhp5gtLCVC1OpGiAXYEztQJckYf/wllHkykSXajvDj
            9OUfKQUbEqUwcuVJrseFSS+EP8BwT8oQgkvUXtQP5uK4cwETCLl8KTVdinpynaRp
            M8lgzD0W9chTRQJSyLDytHXUmqFmU1HkV1ZLXTFI3yit12nCOd2yhIm5MxxmqvbS
            e1YaMU2iGnWGL8xO0LcZhwxVjEu3dNIEFNYr2meEsN8BvK3x3JuKQGVCyJVt0tae
            +NNScQaASxghxAaWjlitpsuV4PhJYQQJAGy4TgtkKiEsh04b/6j0u5omnqSBNHFP
            tUKFCr25lnoG2+6r3EO6//xF6SZxF/yZHWjo5qLJ6XshuTpNRPBzqYMGWX/jFMQD
            ifQiQTD01UdN+4kg9HP/q+DKAxKI5ETrd5so/t2LQ3ya6UACmc/WXecMsnHy8waR
            2bjv0qI24d+31OSUQYMCaegkey96/DQRqYI1830jhxIZEq5X/GuCWplHO7xvHBIv
            LROOIyf/UmIbR8bvDiyIfoFP3Y8Docc87UFI/BKPDP6ql7I9RhjRmw6StXx9VhhX
            NsXxfI2lzqhk3bacMEmRr9MQ/QuHpBaKVjA8bdw+xzP6Fx1NGCU070RXJUl0L6LS
            XgHD31TRYQe1H/xI/ZOWAL4kWQd3VWs+N2SKSVYbOi4qGMOEN029q8VnK6B/Fnwo
            VBTGCvTLucaCwHtAfac6o8nCuHnZ8wT6VV13lnWu4n7BFoq0IbzwRpatLZa6Nqg=
            =buri
            -----END PGP MESSAGE-----
          fp: 2ED21ED3DBBF5A37898D9D316225432F3481C8E0
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
