apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: http-cache
  labels:
    app.kubernetes.io/component: http-cache
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: http-cache
  template:
    metadata:
      labels:
        app.kubernetes.io/component: http-cache
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/component: http-cache
            topologyKey: kubernetes.io/hostname
      containers:
        - name: http-cache
          image: nginx
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: shardconfig
          env:
            - name: PORT
              value: "80"
            - name: ACCOUNTS_SERVER_URL
              value: "http://web-server"
            # - name: NGINX_ENTRYPOINT_QUIET_LOGS
            #   value: "1"
          volumeMounts:
            - name: data
              mountPath: /var/lib/nginx/data
            - name: nginx-config
              mountPath: "/etc/nginx/nginx.conf"
              subPath: nginx.conf
            - name: nginx-config
              mountPath: "/etc/nginx/templates/default.conf.template"
              subPath: default.conf.template
      volumes:
        - name: nginx-config
          configMap:
            name: http-cache-nginx-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: http-cache
  labels:
    app.kubernetes.io/component: http-cache
spec:
  selector:
    app.kubernetes.io/component: http-cache
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: http-cache
  labels:
    app.kubernetes.io/component: http-cache
spec:
  maxUnavailable: 30%
  selector:
    matchLabels:
      app.kubernetes.io/component: http-cache
