apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: isolate-shard-db
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: database
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels: {}
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: postgres-operator
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: monitoring
      podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus
