apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: git-pull-ssh-id
  files:
  # A SOPS-encrypted file containing the SSH private key used to
  # authenticate to the GitOps Git server.
  #
  # Run `ssh-keygen -f id_rsa -N ''` to generate a new SSH
  # private/public key pair. This will create two files:
  # 1. "id_rsa", containing the unencrypted SSH private key;
  # 2. "id_rsa.pub", containing the SSH public key.
  #
  # Then use SOPS to encrypt the "id_rsa" file. The resulting
  # encrypted file must be named "id_rsa.encrypted". For example, you
  # may run: `sops encrypt id_rsa > id_rsa.encrypted`.
  - id_rsa=id_rsa.encrypted

  # The "id_rsa.pub" file generated in the previous step. (See the
  # previous comment.)
  - id_rsa.pub=id_rsa.pub

  # The certificate for the "id_rsa.pub" key. To create this
  # certificate, run this command:
  #
  # $ ssh-keygen -s <path-to-root-ca-private-key-file> -I git-pull -n git id_rsa.pub
  #
  # Here "<path-to-root-ca-private-key-file>" is the path to your
  # Swaptacular node's private key, and "id_rsa.pub" is the public key
  # generated in the previous steps. (See previous comments.)
  - id_rsa-cert.pub=id_rsa-cert.pub

  type: Opaque

- name: regcreds
  files:
  - ".dockerconfigjson=../regcreds.json.encrypted"
  options:
    disableNameSuffixHash: true
  type: kubernetes.io/dockerconfigjson

configMapGenerator:
- name: nfs-server-config
  literals:
  # These variables specify how to connect to the GitOps Git
  # repository, and how often to check (pull) for changes:
  #
  - GIT_SERVER=git-server.simple-git-server.svc.cluster.local
  - GIT_PORT=2222
  - GIT_REPOSITORY_PATH=/srv/git/fluxcd.git
  - GIT_PULL_SECONDS=60

  # The relative path in the GitOps Git repository, to the
  # sub-directory containing the applications' Kustomize overlay that
  # will be running in the Kubernetes cluster.
  - OVERLAY_SUBDIR=apps/dev

  options:
    # These annotations are used as sources for convenient Kustomize
    # replacements:
    #
    annotations:
      # The NFS-server service need a static cluster IP address.
      #
      # Depending on the Kubernetes cluster, the safe range for static
      # cluster IPs will be different, but according to the Kubernetes
      # documentation, is seems that the range from 10.96.0.2 to
      # 10.96.0.15 should always be safe.
      kustomize_nfs_service_cluster_ip: 10.96.0.4

      # Kubernetes memory and CPU requests and limits, for the NFS
      # server containers.
      #
      kustomize_nfs_server_cpu_request: 1m
      kustomize_nfs_server_cpu_limit: 1000m
      kustomize_nfs_server_memory_request: 64Mi
      kustomize_nfs_server_memory_limit: 1Gi
      kustomize_git_pull_cpu_request: 1m
      kustomize_git_pull_cpu_limit: 1000m
      kustomize_git_pull_memory_request: 64Mi
      kustomize_git_pull_memory_limit: 1Gi

# OCI images to use for the different containers:
#
images:
- name: swpt-nfs-server
  newName: ghcr.io/swaptacular/swpt_nfs_server
  digest: sha256:f3674f3a027e961d6c4be308094e1ec129859fda1aafac85e5920edb0c9bdb7f

namespace: swpt-nfs-server

resources:
- ../../base/swpt-nfs-server/

replacements:
- path: ../../base/swpt-nfs-server/replacements/nfs-cluster-ip.yaml
- path: ../../base/swpt-nfs-server/replacements/nfs-server-cpu-limit.yaml
- path: ../../base/swpt-nfs-server/replacements/nfs-server-cpu-request.yaml
- path: ../../base/swpt-nfs-server/replacements/nfs-server-memory-limit.yaml
- path: ../../base/swpt-nfs-server/replacements/nfs-server-memory-request.yaml
- path: ../../base/swpt-nfs-server/replacements/git-pull-cpu-limit.yaml
- path: ../../base/swpt-nfs-server/replacements/git-pull-cpu-request.yaml
- path: ../../base/swpt-nfs-server/replacements/git-pull-memory-limit.yaml
- path: ../../base/swpt-nfs-server/replacements/git-pull-memory-request.yaml
