apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: swpt-accounts-shard
      app.kubernetes.io/part-of: swpt-accounts
resources:
  - shard/
