apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# The name of the namespace could be changed. However, the name of the
# namespace and the name of the directory that contains this
# `kustomization.yaml` file MUST always be the same!
namespace: swpt-debtors

secretGenerator:
- name: spilo-env-secret
  files:
  # Run `openssl rand -base64 32` to generate a random encryption key.
  - WALG_LIBSODIUM_KEY=pg-secrets/spilo-walg-libsodium-key.encrypted

  # The "password" for the S3 service.
  - AWS_SECRET_ACCESS_KEY=pg-secrets/spilo-aws-secret-access-key.encrypted

  literals:
  # The "username" for the S3 service.
  - AWS_ACCESS_KEY_ID=console

  # The endpoint for the S3 service.
  - AWS_ENDPOINT=https://minio.minio-tenant.svc.cluster.local:443

  # When Amazon S3 is used, this specifies the AWS region. In that
  # case, specifying `AWS_ENDPOINT` should not be necessary.
  - AWS_REGION=us-east-1

  # This specifies the trusted CA for the local MinIO S3 server. This
  # should not be necessary for "proper" S3 providers.
  - WALG_S3_CA_CERT_FILE=/certs/minio/ca.crt

  options:
    disableNameSuffixHash: true
    labels:
      app.kubernetes.io/name: swpt-debtors
      application: spilo
      team: swpt
  type: Opaque

- name: db-owner-credentials
  files:
  # A SOPS-encrypted file containing the password for the "db_owner"
  # user on all Postgres clusters which this application will create.
  # Once created, the password must not be changed.
  - password=pg-secrets/postgres-cluster-password.encrypted

  literals:
  - username=db_owner

  options:
    disableNameSuffixHash: true
    labels:
      app.kubernetes.io/name: swpt-debtors
  type: Opaque

- name: server-certificate
  files:
  # The server certificate PEM file. This certificate will be used to
  # authenticate before peer nodes. On how to generate a server
  # certificate, check https://github.com/swaptacular/swpt_ca_scripts
  - server.crt=server.crt

  # A SOPS-encrypted file containing the private key for the server
  # certificate. This private key will be used to authenticate before
  # peer nodes. (See the previous comment.)
  #
  # To SOPS-encrypt the private key, you may use this command:
  #
  # $ sops encrypt server.key > server.key.encrypted
  - server.key=server.key.encrypted

  options:
    labels:
      app.kubernetes.io/name: swpt-debtors
  type: Opaque

- name: swpt-hydra
  files:
  # The "hydra-secret.encrypted" file must be a SOPS-encrypted file
  # containing a cryptographic-grade secret. For example, to generate
  # this file you may use the following commands:
  #
  # $ openssl rand -base64 32 > hydra-secret
  # $ sops encrypt hydra-secret > hydra-secret.encrypted
  # $ shred -z hydra-secret
  # $ rm hydra-secret
  - secretsSystem=hydra-secret.encrypted
  - secretsCookie=hydra-secret.encrypted

  options:
    disableNameSuffixHash: true
    labels:
      app.kubernetes.io/name: hydra
      app.kubernetes.io/instance: swpt
  type: Opaque

configMapGenerator:
- name: debtors-agent-config
  literals:
  # The publicly known domain name of this Swaptacular node.
  - PUBLIC_HOSTNAME=demo.swaptacular.org

  # Debtor IDs are 64-bit integer numbers. The debtors agent is
  # responsible only for debtor IDs which start with the hexadecimal
  # prefix specified in the `./node-data/debtors-subnet.txt` file.
  # Therefore, the values of the `MIN_DEBTOR_ID` and `MAX_DEBTOR_ID`
  # variables must correspond to the content of this file.
  #
  # For example, if the `./node-data/debtors-subnet.txt` file contains
  # the string "abcdef1234", then:
  # 1) `MIN_DEBTOR_ID` must be set to "0xabcdef1234000000";
  # 2) `MAX_DEBTOR_ID` must be set to "0xabcdef1234ffffff".
  #
  # NOTE: Both values are prefixed with "0x", and consist of exactly
  # 16 hexadecimal symbols.
  - MIN_DEBTOR_ID=0x0abcdef100000000
  - MAX_DEBTOR_ID=0x0abcdef100ffffff

  options:
    labels:
      app.kubernetes.io/name: swpt-debtors

- name: swpt-hydra
  files:
  # The configuration file for Ory-Hydra. Can reference a custom
  # configuration file. Normally, the default one should be work
  # reasonably well.
  - hydra.yaml=../../base/swpt-debtors/static/hydra.yaml

  literals:
  # This string will be appended to the "data source name" (DSN)
  # string (after the "?" character). It alters the behaviour of the
  # database driver. For example: the maximum number of open
  # connections, or the maximum number of idle connections.
  - dsn_query_params=max_conns=20&max_idle_conns=4

  # Configure how many records Hydra's janitor retrieves from the
  # database for deletion.
  - janitor_limit=10000

  # Configure how many records Hydra's janitor deletes with each
  # iteration.
  - janitor_batch_size=100

  options:
    labels:
      app.kubernetes.io/name: hydra
      app.kubernetes.io/instance: swpt

    # These annotations are used as sources for convenient Kustomize
    # replacements:
    #
    annotations:
      # Kubernetes memory and CPU requests and limits, for the Ory
      # Hydra server containers.
      #
      kustomize_hydra_cpu_request: 100m
      kustomize_hydra_cpu_limit: 1000m
      kustomize_hydra_memory_request: 128Mi
      kustomize_hydra_memory_limit: 1Gi

- name: stomp-config
  literals:
  # The number of SMP messages that STOMP servers and STOMP clients
  # will buffer in memory.
  - SWPT_SERVER_BUFFER=100
  - SWPT_CLIENT_BUFFER=100

  # The number of worker threads that STOMP servers will use for file
  # access to the NFS server.
  - APP_FILE_READ_THREADS=10

  options:
    labels:
      app.kubernetes.io/name: swpt-debtors

    # These annotations are used as sources for convenient Kustomize
    # replacements:
    #
    annotations:
      # The static cluster IP address of the
      # "nfs-server.swpt-nfs-server.svc.cluster.local" service.
      kustomize_nfs_service_cluster_ip: 10.96.0.4

      # Each Swaptacular node runs its own STOMP server. When running
      # more than one Swaptacular node on a single Kubernetes cluster,
      # you should make sure that the STOMP servers of different
      # Swaptacular nodes listen of different TCP ports.
      kustomize_stomp_server_port: "1235"

      # Kubernetes memory and CPU requests and limits, for the STOMP
      # server containers.
      #
      kustomize_stomp_server_cpu_request: 10m
      kustomize_stomp_server_cpu_limit: 1000m
      kustomize_stomp_server_memory_request: 64Mi
      kustomize_stomp_server_memory_limit: 1Gi

- name: apiproxy-config
  files:
  # The configuration file for the "apiproxy".
  #
  # Each line in the configuration file should start with a route
  # specifier, followed by at least one space, followed by a web
  # server URL (only "http://" server URLs are supported). Route
  # specifiers consist of zero or more 0s or 1s, separated by dots,
  # ending with a hash symbol ("#"). An example configuration file:
  #
  # 0.# http://web-server-0
  # 1.# http://web-server-1
  #
  # or, for a sigle server:
  #
  # # http://web-server
  #
  # Note that the route specifiers in the configuration file must
  # cover all possible bit masks. For example, the following
  # configuration file is invalid:
  #
  # 0.# http://web-server-0
  #
  # because it does not cover sharding keys starting with a
  # binary "1".
  - apiproxy.conf=apiproxy.conf

  options:
    labels:
      app.kubernetes.io/name: swpt-debtors

    # These annotations are used as sources for convenient Kustomize
    # replacements:
    #
    annotations:
      # Kubernetes memory and CPU requests and limits, for the
      # apiproxy server containers.
      #
      kustomize_apiproxy_cpu_request: 100m
      kustomize_apiproxy_cpu_limit: 1000m
      kustomize_apiproxy_memory_request: 128Mi
      kustomize_apiproxy_memory_limit: 1Gi

# The number of replicas for each component. One replica works fine,
# but to have high-availability, should be at least 2.
#
replicas:
- name: apiproxy
  count: 1
- name: stomp-server
  count: 1
- name: swpt-hydra
  count: 1

# OCI images to use for the different containers:
#
images:
- name: swpt-debtors
  newName: ghcr.io/swaptacular/swpt_debtors
  newTag: 2.3.0
- name: swpt-apiproxy
  newName: ghcr.io/swaptacular/swpt_apiproxy
  newTag: 1.2.2
- name: swpt-stomp
  newName: ghcr.io/swaptacular/swpt_stomp
  newTag: 2.3.0
- name: swpt-nfs-server
  newName: ghcr.io/swaptacular/swpt_nfs_server
  newTag: 0.1.6
- name: oryd-hydra-maester
  newName: docker.io/oryd/hydra-maester
  newTag: v0.0.36
- name: oryd-hydra
  newName: docker.io/oryd/hydra
  newTag: v2.3.0

resources:
- ../../base/swpt-debtors/
- broker.yaml
- hydra-db/
- shards/
- node-data/peers/

patches:
- path: ../../base/swpt-debtors/patches/broker.yaml
  target:
    group: rabbitmq.com
    kind: RabbitmqCluster
    name: broker
    version: v1beta1

replacements:
- path: ../../base/swpt-debtors/replacements/nfs-cluster-ip.yaml
- path: ../../base/swpt-debtors/replacements/nfs-pv-name.yaml
- path: ../../base/swpt-debtors/replacements/stomp-server-port.yaml
- path: ../../base/swpt-debtors/replacements/apiproxy-cpu-limit.yaml
- path: ../../base/swpt-debtors/replacements/apiproxy-cpu-request.yaml
- path: ../../base/swpt-debtors/replacements/apiproxy-memory-limit.yaml
- path: ../../base/swpt-debtors/replacements/apiproxy-memory-request.yaml
- path: ../../base/swpt-debtors/replacements/stomp-server-cpu-limit.yaml
- path: ../../base/swpt-debtors/replacements/stomp-server-cpu-request.yaml
- path: ../../base/swpt-debtors/replacements/stomp-server-memory-limit.yaml
- path: ../../base/swpt-debtors/replacements/stomp-server-memory-request.yaml
- path: ../../base/swpt-debtors/replacements/hydra-cluster-role-name.yaml
- path: ../../base/swpt-debtors/replacements/hydra-cpu-limit.yaml
- path: ../../base/swpt-debtors/replacements/hydra-cpu-request.yaml
- path: ../../base/swpt-debtors/replacements/hydra-memory-limit.yaml
- path: ../../base/swpt-debtors/replacements/hydra-memory-request.yaml
