apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-git-server
spec:
  replicas: 1  # must be exactly 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: simple-git-server
  template:
    metadata:
      labels:
        app: simple-git-server
    spec:
      priorityClassName: system-cluster-critical
      containers:
        - image: docker.io/rockstorm/git-server:2.47
          name: git-server
          ports:
            - containerPort: 22
          env:
            - name: SSH_HOST_KEYS_PATH
              value: "/tmp/host-keys"
            - name: SSH_AUTHORIZED_KEYS_FILE
              value: "/etc/ssh/authorized_keys"
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - mountPath: "/srv/git/"
              name: git-repositories
              readOnly: false
            - name: sshd-config
              mountPath: "/etc/ssh/sshd_config"
              subPath: sshd_config
            - name: sshd-config
              mountPath: "/etc/ssh/trusted_user_ca_keys"
              subPath: trusted_user_ca_keys
            - name: host-keys
              mountPath: "/etc/ssh/authorized_keys"
              subPath: ssh_host_rsa_key.pub
            - mountPath: "/tmp/host-keys/"
              name: host-keys
      imagePullSecrets:
        - name: regcreds
      volumes:
        - name: git-repositories
          persistentVolumeClaim:
            claimName: git-repositories
        - name: sshd-config
          configMap:
            name: sshd-config
        - name: host-keys
          secret:
            secretName: host-keys
