apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - network-policies.yaml

configMapGenerator:
- name: nginx-config
  files:
  - nginx.conf=static/nginx.conf
  - default.conf.template=static/default.conf.template

secretGenerator:
- name: nginx-ssl-certificate
  files:
  - cert.pem=static/cert.pem
  - key.pem=static/key.pem
  type: Opaque
