kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: git-repositories
spec:
  accessModes:
    - ReadWriteOnce  # Should be "ReadWriteOncePod", but this is not supported everywhere yet!
  resources:
    requests:
      storage: 1Gi
