apiVersion: v1
kind: Service
metadata:
  name: git-server
spec:
  selector:
    app: simple-git-server
  ports:
    - name: ssh
      protocol: TCP
      appProtocol: ssh
      port: 22
      targetPort: 22
  type: LoadBalancer
