apiVersion: apps/v1
kind: Deployment
metadata:
  name: swpt-creditors-ui
  labels:
    app.kubernetes.io/name: swpt-creditors
    app.kubernetes.io/component: swpt-creditors-ui
    app.kubernetes.io/instance: en
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: swpt-creditors
      app.kubernetes.io/component: swpt-creditors-ui
      app.kubernetes.io/instance: en
  template:
    metadata:
      labels:
        app.kubernetes.io/name: swpt-creditors
        app.kubernetes.io/component: swpt-creditors-ui
        app.kubernetes.io/instance: en
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: swpt-creditors
                app.kubernetes.io/component: swpt-creditors-ui
                app.kubernetes.io/instance: en
            topologyKey: kubernetes.io/hostname
            matchLabelKeys:
            - pod-template-hash
      priorityClassName: user-ui-webserver
      imagePullSecrets:
        - name: regcreds
      containers:
        - name: swpt-creditors-ui
          image: swpt-creditors-ui
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - DAC_OVERRIDE
              - NET_RAW
              - MKNOD
              - SYS_CHROOT
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              # Here "creditors-webapp" will be automatically replaced
              # with the value of the "app.kubernetes.io/instance"
              # label.
              #
              path: /creditors-webapp/
              port: http
            initialDelaySeconds: 5
          envFrom:
            - configMapRef:
                name: swpt-creditors-ui-config
          env:
            - name: PUBLIC_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: creditors-agent-config
                  key: PUBLIC_HOSTNAME
            - name: WEBAPP_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: creditors-agent-config
                  key: WEBAPP_HOSTNAME
            - name: BASE_URL
              # Here "creditors-webapp" will be automatically replaced
              # with the value of the "app.kubernetes.io/instance"
              # label.
              #
              value: /creditors-webapp
            - name: SERVER_API_ENTRYPOINT
              value: https://$(PUBLIC_HOSTNAME)/creditors/.wallet
            - name: AUTHORIZATION_URL
              value: https://$(PUBLIC_HOSTNAME)/oauth2/auth
            - name: TOKEN_URL
              value: https://$(PUBLIC_HOSTNAME)/oauth2/token
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  # Here "en" will be automatically replaced with the
                  # value of the "app.kubernetes.io/instance" label.
                  #
                  name: oauth2-clients.creditors-webapp-en
                  key: CLIENT_ID
            - name: REDIRECT_URL
              value: https://$(WEBAPP_HOSTNAME)$(BASE_URL)/
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 12Mi

---
apiVersion: v1
kind: Service
metadata:
  name: swpt-creditors-ui
  labels:
    app.kubernetes.io/name: swpt-creditors
    app.kubernetes.io/component: swpt-creditors-ui
    app.kubernetes.io/instance: en
spec:
  selector:
    app.kubernetes.io/name: swpt-creditors
    app.kubernetes.io/component: swpt-creditors-ui
    app.kubernetes.io/instance: en
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: swpt-creditors-ui
  labels:
    app.kubernetes.io/name: swpt-creditors
    app.kubernetes.io/component: swpt-creditors-ui
    app.kubernetes.io/instance: en
spec:
  maxUnavailable: 30%
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app.kubernetes.io/name: swpt-creditors
      app.kubernetes.io/component: swpt-creditors-ui
      app.kubernetes.io/instance: en

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-swpt-creditors-ui
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  # Here "namespace" will be automatically replaced with the name of
  # the current namespace.
  #
  ingressClassName: namespace.nginx

  # Here "webapp-hostname" will be automatically replaced with the
  # configured webapp hostname.
  #
  tls:
  - hosts:
    - webapp-hostname
    secretName: acme-cert-key

  rules:
  # Here "webapp-hostname" will be automatically replaced with the
  # configured webapp hostname.
  #
  - host: webapp-hostname
    http:
      paths:
      # Here "creditors-webapp" will be automatically replaced with
      # the value of the "app.kubernetes.io/instance" label.
      #
      - path: /creditors-webapp/
        pathType: Prefix
        backend:
          service:
            name: swpt-creditors-ui
            port:
              name: http

---
apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: creditors-webapp
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  clientName: "Creditors Agent UI"
  grantTypes:
    - authorization_code
  responseTypes:
    - code
  scopeArray:
    - access
    - access.readonly
    - disable_pin
  # Here "en" will be automatically replaced with the value of the
  # "app.kubernetes.io/instance" label.
  #
  secretName: oauth2-clients.creditors-webapp-en
  redirectUris:
    # Here "webapp-hostname" will be automatically replaced with the
    # configured webapp hostname, and "creditors-webapp" will be
    # replaced with the value of the "app.kubernetes.io/instance"
    # label.
    #
    - https://webapp-hostname/creditors-webapp/
  tokenEndpointAuthMethod: none
