apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: cert-manager
  name: forbid-pods-internet-access
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8
    - ipBlock:
        cidr: 172.16.0.0/12
    - ipBlock:
        cidr: 192.168.0.0/16
