apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This must be either an empty string, or a string starting with '-',
# and followed by 0s or 1s. "-101" for example.
nameSuffix: "-0"

labels:
- includeSelectors: true
  pairs:
    # The value for the label must correspond to the "nameSuffix"
    # value. For example, if "nameSuffix" is "-101", the value for the
    # label must be "shard-101". If "nameSuffix" is "", the value for
    # the label must be "shard".
    app.kubernetes.io/instance: shard-0

configMapGenerator:
- name: shardconfig
  literals:
  # The routing key must correspond to the "nameSuffix" value. For
  # example, if "nameSuffix" is "-101", the routing key must be
  # "1.0.1.#". If "nameSuffix" is "", the routing key must be "#".
  - PROTOCOL_BROKER_QUEUE_ROUTING_KEY=0.#

  - PROTOCOL_BROKER_PROCESSES=1
  - PROTOCOL_BROKER_THREADS=3
  - PROTOCOL_BROKER_PREFETCH_COUNT=10

  - CHORES_BROKER_PROCESSES=1
  - CHORES_BROKER_THREADS=3
  - CHORES_BROKER_PREFETCH_COUNT=10

  - WEBSERVER_PROCESSES=1
  - WEBSERVER_THREADS=3

  - FLUSH_PROCESSES=1
  - FLUSH_PERIOD=1.5

  - DELETE_PARENT_SHARD_RECORDS=false
  - FETCH_API_URL=http://accounts-cache:80
  - APP_LOG_LEVEL=warning
  - APP_LOG_FORMAT=json

  options:
    annotations:
      unmodifiedSuffix: do

replicas:
- name: web-server
  count: 1
- name: messages-flusher
  count: 1
- name: messages-consumer
  count: 1
- name: chores-consumer
  count: 1

# The file "postgres-cluster-password.encrypted" referenced here, must
# be an exact copy of the "../../postgres-cluster-password.encrypted"
# file, in the grandparent directory.
#
secretGenerator:
- name: postgres.cluster-name.credentials.postgresql.acid.zalan.do
  files:
  - password=postgres-cluster-password.encrypted
  literals:
  - username=postgres
  options:
    disableNameSuffixHash: true
    labels:
      application: spilo
      cluster-name: cluster-name
      team: swpt
  type: Opaque
- name: standby.cluster-name.credentials.postgresql.acid.zalan.do
  files:
  - password=postgres-cluster-password.encrypted
  literals:
  - username=standby
  options:
    disableNameSuffixHash: true
    labels:
      application: spilo
      cluster-name: cluster-name
      team: swpt
  type: Opaque
- name: db-owner.cluster-name.credentials.postgresql.acid.zalan.do
  files:
  - password=postgres-cluster-password.encrypted
  literals:
  - username=db_owner
  options:
    disableNameSuffixHash: true
    labels:
      application: spilo
      cluster-name: cluster-name
      team: swpt
  type: Opaque

resources:
- ../../../../base/swpt-accounts/shard-template/
- postgres-cluster.yaml

patches:
- path: static/postgres-cluster-patch.yaml
  target:
    group: acid.zalan.do
    kind: postgresql
    name: accounts-db
    version: v1

replacements:
- path: static/secrets-clustername-replacement.yaml
- path: static/secrets-namesuffix-replacement.yaml
- path: static/shardconfig-replacement.yaml
