apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: loki-gateway
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/component: gateway
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: loki
      app.kubernetes.io/component: gateway
  maxUnavailable: 30%
  unhealthyPodEvictionPolicy: AlwaysAllow

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: loki-read
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/component: read
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: loki
      app.kubernetes.io/component: read
  maxUnavailable: 30%
  unhealthyPodEvictionPolicy: AlwaysAllow

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: loki-backend
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/component: backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: loki
      app.kubernetes.io/component: backend
  maxUnavailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: loki-write
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/component: write
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: loki
      app.kubernetes.io/component: write
  maxUnavailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
