apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 10m
  chart:
    spec:
      chart: charts/loki-6.30.1.tgz
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system

  targetNamespace: monitoring
  releaseName: loki
  postRenderers:
    - kustomize:
        images: []
  values:
    global:
      image:
        registry: null
      extraArgs:
        - "-config.expand-env=true"
        - "-log.level=warn"
      extraEnvFrom:
        - secretRef:
            name: loki-object-store
      extraVolumes:
        - name: minio-ca-certificate
          configMap:
            name: kube-root-ca.crt
      extraVolumeMounts:
        - name: minio-ca-certificate
          mountPath: /certs/minio
      priorityClassName: critical-monitoring
    imagePullSecrets:
      - name: regcreds
    loki:
      image:
        repository: grafana/loki
        tag: 3.5.1
        digest: null
      auth_enabled: false
      commonConfig:
        replication_factor: 3
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      storage:
        type: s3
        s3:
          endpoint: "${AWS_ENDPOINT}"
          region: "${AWS_REGION}"
          accessKeyId: "${AWS_ACCESS_KEY_ID}"
          secretAccessKey: "${AWS_SECRET_ACCESS_KEY}"
          s3ForcePathStyle: true
          insecure: false
          http_config:
            # This specifies the trusted CA for the local MinIO S3
            # server. This should not be necessary for "proper" S3
            # providers.
            ca_file: /certs/minio/ca.crt
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
          admin: loki-admin
      ingester:
        lifecycler:
          ring:
            # The default is 1 minute. Note that the similar setting
            # `ingester.lifecycler.heartbeat_timeout` seems to be
            # deprecated, but this is not mentioned in the docs.
            heartbeat_timeout: 1m
        chunk_idle_period: 1h
        chunk_encoding: snappy
        wal:
          # Maximum memory size the WAL may use during replay. After
          # hitting this, it will flush data to storage before
          # continuing. A unit suffix (KB, MB, GB) may be applied. The
          # default is 4GB. Normally, this should be about 75% of the
          # memory request for the ingester pods.
          replay_memory_ceiling: 4GB
      querier:
        # Default is 4, if you have enough memory and CPU you can
        # increase, reduce if OOMing.
        max_concurrent: 4
      compactor:
        retention_enabled: true
        delete_request_store: s3
      limits_config:
        retention_period: 30d
        max_query_lookback: 30d  # Should be the same as `retention_period`.
        volume_enabled: true
    write:
      replicas: 3
      persistence:
        size: 10Gi
        storageClass: null
      resources: {}
    read:
      replicas: 1
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/component: read
              topologyKey: kubernetes.io/hostname
              matchLabelKeys:
              - pod-template-hash
      resources: {}
    backend:
      replicas: 1
      persistence:
        size: 10Gi
        storageClass: null
      resources: {}
    chunksCache:
      replicas: 1
      allocatedMemory: 8192
      priorityClassName: critical-monitoring
      persistence:
        enabled: true
        storageSize: 20Gi
        storageClass: null
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/component: memcached-chunks-cache
            topologyKey: kubernetes.io/hostname
    resultsCache:
      replicas: 1
      allocatedMemory: 1024
      priorityClassName: critical-monitoring
      persistence:
        enabled: true
        storageSize: 5Gi
        storageClass: null
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/component: memcached-results-cache
            topologyKey: kubernetes.io/hostname
    lokiCanary:
      image:
        repository: grafana/loki-canary
        tag: 3.5.1
        digest: null
      resources: {}
    gateway:
      replicas: 1
      verboseLogging: false
      image:
        repository: nginxinc/nginx-unprivileged
        tag: 1.28-alpine
        digest: null
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/component: gateway
              topologyKey: kubernetes.io/hostname
              matchLabelKeys:
              - pod-template-hash
      resources: {}
    sidecar:
      image:
        # The registry must be included in the "repository" value
        # ("docker.io" for example), because the chart ignores the
        # value of "global.image.registry" for sidecars.
        repository: docker.io/kiwigrid/k8s-sidecar
        tag: 1.30.3
        sha: ""
      resources: {}
    memcached:
      image:
        repository: memcached
        tag: 1.6.38-alpine
    memcachedExporter:
      image:
        repository: prom/memcached-exporter
        tag: v0.15.3
      resources: {}
    test:
      enabled: false
