apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
spec:
  interval: 10m
  chart:
    spec:
      chart: charts/promtail-6.17.0.tgz
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system

  targetNamespace: monitoring
  releaseName: promtail
  postRenderers:
    - kustomize:
        images: []
  values:
    priorityClassName: critical-monitoring
    imagePullSecrets:
      - name: regcreds
    image:
      # Do not change these! Use "postRenderers/kustomize/images" instead.
      registry: docker.io
      repository: grafana/promtail
      tag: "3.5.1"
    resources: {}
    config:
      logLevel: info
      logFormat: logfmt
      clients:
        - url: http://loki-write:3100/loki/api/v1/push
      snippets:
        extraRelabelConfigs:
          - source_labels:
              - __meta_kubernetes_pod_label_log_pipeline
            action: replace
            target_label: meta_log_pipeline

        pipelineStages:
          # This is always needed.
          - cri: {}

          # The "swpt-python-logging" log pipeline:
          - match:
              selector: '{meta_log_pipeline="swpt-python-logging",container!~"^await-migrations|configure$"}'
              stages:
                # Remove Oathkeeper welcome messages.
                - drop:
                    expression: '^($|Thank you for using ORY Oathkeeper|Take security seriously and subscribe to the ORY Security Newsletter|>> Subscribe now: \S+ <<)'

                # Try to parse the log message as JSON.
                - json:
                    expressions:
                      asctime: asctime
                      levelname: levelname
                    drop_malformed: false

                # Lowercase the parsed "levelname" field. Make it a label.
                - template:
                    source: levelname
                    template: '{{ ToLower .Value }}'
                - labels:
                    level: levelname

                # For JSON messages: Set the timestamp.
                - match:
                    selector: '{level!=""}'
                    stages:
                      - timestamp:
                          source: asctime
                          format: 2006-01-02T15:04:05-0700

                # For plain text messages: Assign an "error" level.
                - match:
                    selector: '{level=""}'
                    stages:
                      - static_labels:
                          level: 'error'

          # Remove extra labels.
          - labeldrop:
              - meta_log_pipeline
