apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
spec:
  interval: 10m
  chart:
    spec:
      chart: charts/promtail-6.17.0.tgz
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system

  targetNamespace: monitoring
  releaseName: promtail
  values:
    config:
    # publish data to loki
      clients:
        - url: http://loki-write:3100/loki/api/v1/push
          tenant_id: 1
