apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: broker
  labels:
    app.kubernetes.io/name: swpt-accounts
    app.kubernetes.io/component: message-broker
spec:
  rabbitmq:
    additionalPlugins:
      - rabbitmq_management
      - rabbitmq_random_exchange
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      minDomains: 3
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: broker
