apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: broker
  labels:
    app.kubernetes.io/name: swpt-accounts
    app.kubernetes.io/component: message-broker
spec:
  rabbitmq:
    additionalPlugins:
      - rabbitmq_management
      - rabbitmq_random_exchange
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: broker
          topologyKey: kubernetes.io/hostname
        weight: 1
