apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: broker
  labels:
    app.kubernetes.io/name: swpt-accounts
    app.kubernetes.io/component: message-broker
spec:
  replicas: 3
  rabbitmq:
    additionalPlugins:
      - rabbitmq_random_exchange
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: broker
        topologyKey: kubernetes.io/hostname

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: broker
  labels:
    app.kubernetes.io/name: swpt-accounts
    app.kubernetes.io/component: message-broker
spec:
  maxUnavailable: 20%
  selector:
    matchLabels:
      app.kubernetes.io/name: broker
