apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ingress-nginx
  labels:
    release: prometheus
    application: ingress-nginx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: controller
  podMetricsEndpoints:
  - port: metrics
