apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- broker-pdb.yaml
- broker-policies.yaml
- broker-service-monitor.yaml
- apiproxy.yaml
- nfs-pvc.yaml
- stomp-server.yaml
- network-policies.yaml
- ingress-nginx.yaml
- ingress-rules.yaml
- ingress-nginx-pod-monitor.yaml
- acme-cert-issuer.yaml
- spilo-pod-monitor.yaml
