apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: swpt-accounts

# IMPORTANT NOTE:
#
# 1. To generate a random `WALG_LIBSODIUM_KEY`, run `openssl rand -base64 32`.
#
# 2. `AWS_SECRET_ACCESS_KEY` is the "password" for the S3 service.
#
# 3. `AWS_ACCESS_KEY_ID` is the "username" for the S3 service.
#
# 4. When Amazon S3 is used, add `- AWS_REGION=your-aws-region` to
#    specify the AWS region ("us-east-1" for example). In this case,
#    specifying `AWS_ENDPOINT` should not be necessary.
#
# 5. `WALG_S3_CA_CERT_FILE` specifies the trusted CA for the local
#    MinIO S3 server. This should not be necessary for "proper" S3
#    providers.

secretGenerator:
- name: spilo-env-secret
  files:
  - WALG_LIBSODIUM_KEY=spilo-walg-libsodium-key.encrypted
  - AWS_SECRET_ACCESS_KEY=spilo-aws-secret-access-key.encrypted
  literals:
  - AWS_ACCESS_KEY_ID=console
  - AWS_ENDPOINT=https://minio.minio-tenant.svc.cluster.local:443
  - WALG_S3_CA_CERT_FILE=/certs/minio/ca.crt
  options:
    disableNameSuffixHash: true
    labels:
      app.kubernetes.io/name: swpt-accounts
      application: spilo
      team: swpt
- name: db-owner-credentials
  files:
  - password=postgres-cluster-password.encrypted
  literals:
  - username=db_owner
  options:
    disableNameSuffixHash: true
    labels:
      app.kubernetes.io/name: swpt-accounts
  type: Opaque

configMapGenerator:
- name: apiproxy-config
  files:
  - apiproxy.conf=apiproxy.conf
  options:
    labels:
      app.kubernetes.io/name: swpt-accounts

images:
- name: swpt-accounts
  newName: ghcr.io/swaptacular/swpt_accounts
  newTag: 2.3.1
- name: swpt-apiproxy
  newName: ghcr.io/swaptacular/swpt_apiproxy
  newTag: 1.2.1

replicas:
- name: apiproxy
  count: 2

resources:
- namespace.yaml
- broker.yaml
- broker-pdb.yaml
- apiproxy.yaml
- apiproxy-pdb.yaml
- apiproxy-service.yaml
- shards/
