apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-data
  labels:
    app.kubernetes.io/name: swpt-accounts
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: swpt-nfs

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: swpt-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # Here "0.0.0.0" will be automatically replaced by the IP address
    # of "nfs-server.swpt-accounts.svc.cluster.local".
    server: 0.0.0.0
    path: "/"
  mountOptions:
    # The effect of these mount options will be that when the NFS
    # server becomes unavailable, 4 re-connection attempts will be
    # made before an error gets raised. The respective re-connection
    # attempts will be made after pauses of 50s, 100s, 150s, and 200s.
    # Therefore, error will not be raised if the NFS server becomes
    # available again within 8.3 minutes.
    - soft
    - timeo=500 # 500 deciseconds
    - retrans=4
