apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-data
  labels:
    app.kubernetes.io/name: swpt-accounts
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: swpt-nfs

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: swpt-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # Here "0.0.0.0" will be automatically replaced by the IP address
    # of "nfs-server.swpt-accounts.svc.cluster.local".
    server: 0.0.0.0
    path: "/"
  mountOptions:
    - soft
    - timeo=500 # 50 seconds before the first retrans
    - retrans=4 # get an error after the 4th failure
