apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-data
  labels:
    app.kubernetes.io/name: swpt-accounts
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: swpt-nfs

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: swpt-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.96.0.2  # nfs-server.swpt-accounts.svc.cluster.local
    path: "/"

  # mountOptions:
  #   - nfsvers=4.2
