apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spilo
  labels:
    release: prometheus
    application: spilo
spec:
  selector:
    matchLabels:
      application: spilo
  podTargetLabels:
    - cluster-name
    - spilo-role
  podMetricsEndpoints:
  - portNumber: 8008  # Patroni
    relabelings:
      - sourceLabels: [__meta_kubernetes_pod_label_cluster_name]
        targetLabel: service
  - port: exporter  # Posgtgres exporter
  - port: backup-exporter  # WALG exporter
