apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: patroni-clusters
  labels:
    release: prometheus
    application: spilo
spec:
  selector:
    matchLabels:
      application: spilo
  podTargetLabels:
    - cluster-name
    - spilo-role
  podMetricsEndpoints:
  - portNumber: 8008

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres-exporters
  labels:
    release: prometheus
    application: spilo
spec:
  selector:
    matchLabels:
      application: spilo
  podTargetLabels:
    - cluster-name
    - spilo-role
  podMetricsEndpoints:
  - port: exporter

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: walg-exporters
  labels:
    release: prometheus
    application: spilo
spec:
  selector:
    matchLabels:
      application: spilo
  podTargetLabels:
    - cluster-name
    - spilo-role
  podMetricsEndpoints:
  - port: backup-exporter
