apiVersion: apps/v1
kind: Deployment
metadata:
  name: stomp-server
  labels:
    app.kubernetes.io/name: swpt-accounts
    app.kubernetes.io/component: stomp-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: swpt-accounts
      app.kubernetes.io/component: stomp-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: swpt-accounts
        app.kubernetes.io/component: stomp-server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: swpt-accounts
                app.kubernetes.io/component: stomp-server
            topologyKey: kubernetes.io/hostname
            matchLabelKeys:
            - pod-template-hash
      priorityClassName: smp-receiver
      containers:
        - name: stomp-server
          image: swpt-stomp
          args: ['swpt-server']
          # securityContext:
          #   capabilities:
          #     add: ["SYS_ADMIN"]
          ports:
            - name: stomp
              containerPort: 1234
          readinessProbe:
            tcpSocket:
              port: stomp
            initialDelaySeconds: 5
          volumeMounts:
            - name: nfs
              mountPath: "/var/lib/swpt-nodedata"
              # subPath: apiproxy.conf
            - name: server-certificate
              mountPath: "/etc/swpt"
          envFrom:
            - secretRef:
                name: broker-default-user
              prefix: rmq_
          env:
            - name: SWPT_SERVER_PORT
              value: "1234"
            - name: SWPT_SERVER_CERT
              value: /etc/swpt/server.crt
            - name: SWPT_SERVER_KEY
              value: /etc/swpt/server.key
            - name: SWPT_SERVER_BUFFER
              value: "100"
            - name: SWPT_NODEDATA_URL
              value: "file:///var/lib/swpt-nodedata/apps/dev/swpt-accounts/nodedata"
            - name: PROTOCOL_BROKER_URL
              value: "$(rmq_connection_string)"
            - name: APP_LOG_LEVEL
              value: warning
            - name: APP_LOG_FORMAT
              value: json
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: nfs
          nfs:
            server: 10.96.0.2
            path: /
            readOnly: true
        - name: server-certificate
          secret:
            secretName: server-certificate

---
apiVersion: v1
kind: Service
metadata:
  name: stomp-server
  labels:
    app.kubernetes.io/name: swpt-accounts
    app.kubernetes.io/component: stomp-server
spec:
  selector:
    app.kubernetes.io/name: swpt-accounts
    app.kubernetes.io/component: stomp-server
  ports:
    - name: stomp
      port: 1234
      protocol: TCP
      targetPort: stomp
  type: LoadBalancer

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: stomp-server
  labels:
    app.kubernetes.io/name: swpt-accounts
    app.kubernetes.io/component: stomp-server
spec:
  maxUnavailable: 30%
  selector:
    matchLabels:
      app.kubernetes.io/name: swpt-accounts
      app.kubernetes.io/component: stomp-server
