apiVersion: apps/v1
kind: Deployment
metadata:
  name: stomp-server
  labels:
    app.kubernetes.io/name: swpt-accounts
    app.kubernetes.io/component: stomp-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: swpt-accounts
      app.kubernetes.io/component: stomp-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: swpt-accounts
        app.kubernetes.io/component: stomp-server
        log.pipeline: swpt-python-logging
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: swpt-accounts
                app.kubernetes.io/component: stomp-server
            topologyKey: kubernetes.io/hostname
            matchLabelKeys:
            - pod-template-hash
      priorityClassName: smp-receiver
      imagePullSecrets:
        - name: regcreds
      containers:
        - name: stomp-server
          image: swpt-stomp
          args: ['swpt-server']
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          ports:
            - name: stomp
              containerPort: 1234
          readinessProbe:
            tcpSocket:
              port: stomp
            initialDelaySeconds: 5
          volumeMounts:
            - name: node-data
              mountPath: "/var/lib/swpt"
              readOnly: true
            - name: server-certificate
              mountPath: "/etc/swpt"
          envFrom:
            - secretRef:
                name: broker-default-user
              prefix: rmq_
            - configMapRef:
                name: stomp-config
          env:
            - name: APP_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SWPT_SERVER_PORT
              value: "1234"
            - name: SWPT_SERVER_CERT
              value: /etc/swpt/server.crt
            - name: SWPT_SERVER_KEY
              value: /etc/swpt/server.key
            - name: SWPT_NODEDATA_URL
              value: "file:///var/lib/swpt/.overlay/$(APP_K8S_NAMESPACE)/node-data"
            - name: PROTOCOL_BROKER_URL
              value: "$(rmq_connection_string)"
            - name: APP_LOG_LEVEL
              value: warning
            - name: APP_LOG_FORMAT
              value: json
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 64Mi
      volumes:
        - name: node-data
          persistentVolumeClaim:
            claimName: node-data
        - name: server-certificate
          secret:
            secretName: server-certificate

---
apiVersion: v1
kind: Service
metadata:
  name: stomp-server
  labels:
    app.kubernetes.io/name: swpt-accounts
    app.kubernetes.io/component: stomp-server
spec:
  selector:
    app.kubernetes.io/name: swpt-accounts
    app.kubernetes.io/component: stomp-server
  ports:
    - name: stomp
      port: 1234
      protocol: TCP
      targetPort: stomp

  # When "externalTrafficPolicy" is "Cluster", the client IPs will be
  # unknown to the server. To preserve the client IPs, this should be
  # set to "Local", in which case most providers will preserve the
  # client IPs, but not all of them will do that. Digital Ocean, for
  # example, requires you to also add this annotation to the service:
  # `service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"`,
  # and then change the server to work with "Proxy protocol" (see
  # https://seriousben.com/posts/2020-02-exploring-the-proxy-protocol/).
  #
  externalTrafficPolicy: Cluster

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: stomp-server
  labels:
    app.kubernetes.io/name: swpt-accounts
    app.kubernetes.io/component: stomp-server
spec:
  maxUnavailable: 30%
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app.kubernetes.io/name: swpt-accounts
      app.kubernetes.io/component: stomp-server
