apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# You may edit this section to specify different OCI images to use for
# the controllers. Also, it is recommended to specify an image digest
# instead of an image tag ("digest: <DIGEST>", instead of "newTag:
# <TAG>").
#
images:

# Minio operator:
- name: minio/operator:v6.0.4
  newName: minio/operator
  digest: sha256:3b00b4de407a0be25a13d69faf4dc2727064b6bbbd89050c494fc768a433a755

# Postgres operator:
- name: ghcr.io/zalando/postgres-operator:v1.14.0
  newName: ghcr.io/zalando/postgres-operator
  digest: sha256:4f40cfc2283b8389ff2e85c3af17c428dee29963be20ddb28b451ead9984b6a9

# DragonflyDB operator:
- name: docker.dragonflydb.io/dragonflydb/operator:v1.1.11
  newName: docker.dragonflydb.io/dragonflydb/operator
  digest: sha256:11cef45ec1079b9d97930fc99ecd08ba29d4eca55cdb45887cb0ac40ee4e4d24
- name: quay.io/brancz/kube-rbac-proxy:v0.16.0
  newName: quay.io/brancz/kube-rbac-proxy
  digest: sha256:2c8f8c357ff87b8bc5df4d967d5f52a23528c5e9c025f9aaa653a9ef4747585f

# Cert-manager:
- name: quay.io/jetstack/cert-manager-cainjector:v1.17.2
  newName: quay.io/jetstack/cert-manager-cainjector
  digest: sha256:ec56edb1161dbcdcb60b5408dd040c877b9f70161b71270c6439ad185796b5b7
- name: quay.io/jetstack/cert-manager-controller:v1.17.2
  newName: quay.io/jetstack/cert-manager-controller
  digest: sha256:2c314feeb5e8b1a250a93be96542f086abc9df2de8e1a0cd7bd491cc7cc7ac08
- name: quay.io/jetstack/cert-manager-webhook:v1.17.2
  newName: quay.io/jetstack/cert-manager-webhook
  digest: sha256:37b16a9dff004a755e5be11a4369aea4d5dd5895f98e1f7def886adca7f5c7b6

# RabbitMQ operators:
- name: rabbitmqoperator/cluster-operator:2.12.1
  newName: rabbitmqoperator/cluster-operator
  digest: sha256:0a7bd7f368168995b94303df54f246d5da67986cef3f5611884499d5d6abcf1b
- name: rabbitmqoperator/messaging-topology-operator:1.17.2
  newName: rabbitmqoperator/messaging-topology-operator
  digest: sha256:c55bea19b4db1e7c54ae0e4a7aa62a5a33a1bd8ceb906d0e3eecca5f33f14b36

# Metrics server:
- name: registry.k8s.io/metrics-server/metrics-server:v0.7.2
  newName: registry.k8s.io/metrics-server/metrics-server
  digest: sha256:ffcb2bf004d6aa0a17d90e0247cf94f2865c8901dcab4427034c341951c239f9

patches:

# This patch is sometimes needed (in "KinD" clusters for example) in
# order for the metrics-server to work. It simply adds
# "--kubelet-insecure-tls" to the list of arguments for the metrics
# server process. Comment this section out if this does not apply to
# your cluster.
- target:
    version: v1
    kind: Deployment
    name: metrics-server
    namespace: kube-system
  path: ../../base/controllers/metrics-server/patches/kubelet-insecure-tls.yaml

# This patch configures the CPU and memory requests for the metrics
# server pod. The default is cpu: 100m, and memory: 200Mi, which
# should be enough for clusters with up to 100 nodes. For clusters of
# more than 100 nodes, additional: 1m core per node, and 2MiB memory
# per node should be requested.
- target:
    version: v1
    kind: Deployment
    name: metrics-server
    namespace: kube-system
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests
      value:
        cpu: 5m
        memory: 50Mi

# This patch configures the CPU and memory requests and limits for the
# Postgres operator pod.
- target:
    kind: Deployment
    name: postgres-operator
    namespace: postgres-operator
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 1m
          memory: 33Mi
        limits:
          cpu: 500m
          memory: 500Mi

# This patch configures the CPU and memory requests and limits for the
# RabbitMQ cluster operator pod.
- target:
    kind: Deployment
    name: rabbitmq-cluster-operator
    namespace: rabbitmq-system
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 1m
          memory: 24Mi
        limits:
          cpu: 200m
          memory: 500Mi

# This patch configures the CPU and memory requests and limits for the
# RabbitMQ messaging topology operator pod.
- target:
    kind: Deployment
    name: messaging-topology-operator
    namespace: rabbitmq-system
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 1m
          memory: 28Mi
        limits:
          cpu: 300m
          memory: 500Mi

# This patch configures the CPU and memory requests and limits for the
# Cert-manager's controller pod.
- target:
    kind: Deployment
    name: cert-manager
    namespace: cert-manager
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 1m
          memory: 30Mi
        limits:
          cpu: 100m
          memory: 500Mi

# This patch configures the CPU and memory requests and limits for the
# Cert-manager's cainjector pod.
- target:
    kind: Deployment
    name: cert-manager-cainjector
    namespace: cert-manager
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 1m
          memory: 39Mi
        limits:
          cpu: 100m
          memory: 500Mi

# This patch configures the CPU and memory requests and limits for the
# Cert-manager's webhook pod.
- target:
    kind: Deployment
    name: cert-manager-webhook
    namespace: cert-manager
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 1m
          memory: 20Mi
        limits:
          cpu: 100m
          memory: 500Mi

# This patch configures the CPU and memory requests and limits for the
# DrabonflyDB operator pod. The first container
# (`/spec/template/spec/containers/0/resources`) is the
# kube-rbac-proxy sidecar, and the second container
# (`/spec/template/spec/containers/1/resources`) is the DragonflyDB
# operator.
- target:
    kind: Deployment
    name: dragonfly-operator-controller-manager
    namespace: dragonfly-operator-system
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 5m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 128Mi
    - op: replace
      path: /spec/template/spec/containers/1/resources
      value:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 128Mi

# This patch configures the Minio operator pod.
# `/spec/template/spec/containers/0/resources` configures the CPU,
# memory, and ephemeral-storage requests and limits, and
# `/spec/template/spec/containers/0/env/-` configures the OCI
# container image used for tenants' sidecars. The default image for
# the sidecars is "quay.io/minio/operator-sidecar:v6.0.2".
- target:
    kind: Deployment
    name: minio-operator
    namespace: minio-operator
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 1m
          memory: 24Mi
          ephemeral-storage: 500Mi
        limits:
          cpu: 500m
          memory: 500Mi
          ephemeral-storage: 2Gi
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: OPERATOR_SIDECAR_IMAGE
        value: quay.io/minio/operator-sidecar@sha256:8d99fd33b4934816bef415b1d4a14cd8238d29ba509591a4502ffd95dbf6a9f5

secretGenerator:
- name: regcreds
  namespace: cert-manager
  files:
  - ".dockerconfigjson=../regcreds.json.encrypted"
  options:
    disableNameSuffixHash: true
  type: kubernetes.io/dockerconfigjson

- name: regcreds
  namespace: dragonfly-operator-system
  files:
  - ".dockerconfigjson=../regcreds.json.encrypted"
  options:
    disableNameSuffixHash: true
  type: kubernetes.io/dockerconfigjson

- name: regcreds
  namespace: postgres-operator
  files:
  - ".dockerconfigjson=../regcreds.json.encrypted"
  options:
    disableNameSuffixHash: true
  type: kubernetes.io/dockerconfigjson

- name: regcreds
  namespace: rabbitmq-system
  files:
  - ".dockerconfigjson=../regcreds.json.encrypted"
  options:
    disableNameSuffixHash: true
  type: kubernetes.io/dockerconfigjson

- name: regcreds
  namespace: monitoring
  files:
  - ".dockerconfigjson=../regcreds.json.encrypted"
  options:
    disableNameSuffixHash: true
  type: kubernetes.io/dockerconfigjson

- name: regcreds
  namespace: kube-system
  files:
  - ".dockerconfigjson=../regcreds.json.encrypted"
  options:
    disableNameSuffixHash: true
  type: kubernetes.io/dockerconfigjson

- name: regcreds
  namespace: minio-operator
  files:
  - ".dockerconfigjson=../regcreds.json.encrypted"
  options:
    disableNameSuffixHash: true
  type: kubernetes.io/dockerconfigjson

resources:
- ../../base/controllers/
