apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio-operator

commonAnnotations:
  operator.min.io/authors: "MinIO, Inc."
  operator.min.io/license: "AGPLv3"
  operator.min.io/support: "https://subnet.min.io"
  operator.min.io/version: v6.0.4

commonLabels:
  app.kubernetes.io/name: operator

resources:
  - namespace.yaml
  - service-account.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - service.yaml
  - deployment.yaml
