apiVersion: v1
kind: Service
metadata:
  name: pebble
  namespace: pebble
spec:
  type: ClusterIP
  ports:
    - port: 14000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: pebble
