apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- tasks-processor.yaml
- messages-flusher.yaml
- messages-consumer.yaml
- messages-drainer.yaml
- web-server.yaml
- network-policies.yaml
