apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rules
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
spec:
  # Here "namespace" will be automatically replaced with the name of
  # the current namespace.
  #
  ingressClassName: namespace.nginx

  rules:
  # Here "public-hostname" will be automatically replaced with the
  # real public hostname of the Swaptacular node.
  #
  - host: public-hostname
    http:
      paths:
      - path: /(oauth2/.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: swpt-hydra-public
            port:
              name: http
      - path: /(debtors/.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: apiproxy
            port:
              name: http
