apiVersion: v1
kind: Namespace
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    app.kubernetes.io/name: swpt-debtors
    app.kubernetes.io/part-of: swpt-nodeset
  name: swpt-debtors
