apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-data
  labels:
    app.kubernetes.io/name: swpt-debtors
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: swpt-nfs
