apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-data
  labels:
    app.kubernetes.io/name: swpt-debtors
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi

  # Here the name of the current namespace will be automatically added
  # to the volumeName ("swpt-nfs-swpt-debtors" for example).
  volumeName: swpt-nfs

---
apiVersion: v1
kind: PersistentVolume
metadata:
  # Here the name of the current namespace will be automatically added
  # to PV's name ("swpt-nfs-swpt-debtors" for example).
  name: swpt-nfs
spec:
  storageClassName: ""
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # Here "0.0.0.0" will be automatically replaced by the IP address
    # of the "nfs-server.swpt-nfs-server.svc.cluster.local" service.
    server: 0.0.0.0
    path: "/"
  mountOptions:
    # The effect of these mount options will be that when the NFS
    # server becomes unavailable, 4 re-connection attempts will be
    # made before an error gets raised. The respective re-connection
    # attempts will be made after pauses of 50s, 100s, 150s, and 200s.
    # Therefore, error will not be raised if the NFS server becomes
    # available again within 500 seconds (~8.3 minutes).
    - soft
    - timeo=500 # 500 deciseconds
    - retrans=4
