apiVersion: v1
kind: Service
metadata:
  name: ory-hydra-admin
  labels:
    app.kubernetes.io/name: swpt-debtors
    app.kubernetes.io/component: ory-hydra
spec:
  selector:
    app.kubernetes.io/name: swpt-debtors
    app.kubernetes.io/component: ory-hydra
  ports:
    - name: admin
      port: 80
      protocol: TCP
      targetPort: admin
