apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: debtors-webapp
spec:
  clientName: "Debtors Agent UI"
  grantTypes:
    - authorization_code
  responseTypes:
    - code
  scopeArray:
    - access
    - access.readonly
  secretName: oauth2-clients.debtors-webapp
  redirectUris:
    # Here "hostname" will be automatically replaced with the public
    # hostname of the Swaptacular node.
    - https://hostname/debtors-webapp/
  tokenEndpointAuthMethod: none

---
apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: swagger-ui
spec:
  clientName: "Swagger UI"
  grantTypes:
    - authorization_code
  responseTypes:
    - code
  scopeArray:
    - access
    - access.readonly
  secretName: oauth2-clients.swagger-ui
  redirectUris:
    # Here "hostname" will be automatically replaced with the public
    # hostname of the Swaptacular node.
    - https://hostname/debtors-swagger-ui/oauth2-redirect.html
  tokenEndpointAuthMethod: client_secret_post

---
apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: debtors-supervisor
spec:
  clientName: "This is the debtors supervisor."
  grantTypes:
    - client_credentials
    - refresh_token
  responseTypes:
    - token
  scopeArray:
    - access.readonly
    - activate
  secretName: oauth2-clients.debtors-supervisor
  tokenEndpointAuthMethod: client_secret_basic

---
apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: debtors-superuser
spec:
  clientName: "This is the debtors superuser."
  grantTypes:
    - client_credentials
    - refresh_token
  responseTypes:
    - token
  scopeArray:
    - access
    - access.readonly
    - activate
    - deactivate
    - restrict
  secretName: oauth2-clients.debtors-superuser
  tokenEndpointAuthMethod: client_secret_basic
