apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cert-manager
  name: cert-manager-cainjector
spec:
  template:
    spec:
      priorityClassName: critical-operator
      imagePullSecrets:
        - name: regcreds
      containers:
        - name: cert-manager-cainjector
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 32Mi
