apiVersion: v1
kind: ConfigMap
metadata:
  name: spilo-env-config
  namespace: postgres-operator
data:
  BACKUP_SCHEDULE: '00 01 * * *'
  BACKUP_NUM_TO_RETAIN: "5"
  WAL_S3_BUCKET: swpt
  WAL_BUCKET_SCOPE_PREFIX: ""
  WAL_BUCKET_SCOPE_SUFFIX: ""
  USE_WALG_BACKUP: "true"
  USE_WALG_RESTORE: "true"
  AWS_S3_FORCE_PATH_STYLE: "true"
  WALG_DISABLE_S3_SSE: "true"
  WALG_LIBSODIUM_KEY_TRANSFORM: base64
  CLONE_METHOD: CLONE_WITH_WALE
  CLONE_WAL_S3_BUCKET: swpt
  CLONE_WAL_BUCKET_SCOPE_PREFIX: ""
  CLONE_WAL_BUCKET_SCOPE_SUFFIX: ""
  CLONE_USE_WALG_BACKUP: "true"
  CLONE_USE_WALG_RESTORE: "true"
  CLONE_AWS_S3_FORCE_PATH_STYLE: "true"
  CLONE_WALG_DISABLE_S3_SSE: "true"
  CLONE_WALG_LIBSODIUM_KEY_TRANSFORM: base64
  STANDBY_WALE_ENV_DIR: "/run/etc/wal-e.d/env-standby"
  STANDBY_WAL_S3_BUCKET: swpt
  STANDBY_WAL_BUCKET_SCOPE_PREFIX: ""
  STANDBY_WAL_BUCKET_SCOPE_SUFFIX: ""
  STANDBY_USE_WALG_BACKUP: "true"
  STANDBY_USE_WALG_RESTORE: "true"
  STANDBY_AWS_S3_FORCE_PATH_STYLE: "true"
  STANDBY_WALG_DISABLE_S3_SSE: "true"
  STANDBY_WALG_LIBSODIUM_KEY_TRANSFORM: base64
