apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dragonfly
  labels:
    app.kubernetes.io/name: dragonfly
spec:
  minAvailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app.kubernetes.io/name: dragonfly
