apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

# You may edit the following lines to specify image digests instead of
# image tags for the FluxCD images (using "digest: <the digest>"
# instead of "newTag: <the tag>").
images:
- name: ghcr.io/fluxcd/source-controller:v1.4.1
  newName: ghcr.io/fluxcd/source-controller
  newTag: v1.4.1
- name: ghcr.io/fluxcd/kustomize-controller:v1.4.0
  newName: ghcr.io/fluxcd/kustomize-controller
  newTag: v1.4.0
- name: ghcr.io/fluxcd/helm-controller:v1.1.0
  newName: ghcr.io/fluxcd/helm-controller
  newTag: v1.1.0
- name: ghcr.io/fluxcd/notification-controller:v1.4.0
  newName: ghcr.io/fluxcd/notification-controller
  newTag: v1.4.0
