apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

# You may edit the following lines to specify image digests instead of
# image tags for the FluxCD images.
images:
- name: ghcr.io/fluxcd/source-controller:v1.4.1
  newName: ghcr.io/fluxcd/source-controller
  digest: sha256:3c5f0f022f990ffc0daf00e5b199548fc0fa6e7119e972318f0267081a332963
- name: ghcr.io/fluxcd/kustomize-controller:v1.4.0
  newName: ghcr.io/fluxcd/kustomize-controller
  digest: sha256:e3b0cf847e9cdf47b19af0fbcfe22786b80b598e0caeea8b6d2a5f9c26a48a24
- name: ghcr.io/fluxcd/helm-controller:v1.1.0
  newName: ghcr.io/fluxcd/helm-controller
  digest: sha256:4c75ca6c24ceb1f1bd7e935d9287a93e4f925c512f206763ec5a47de3ef3ff48
- name: ghcr.io/fluxcd/notification-controller:v1.4.0
  newName: ghcr.io/fluxcd/notification-controller
  digest: sha256:425309a159b15e07f7d97622effc79bc432a37ed55289dd465d37fa217a92a7d
