apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: accounts-db
spec:
  postgresql:
    version: "17"
  volume:
    size: 1Gi
  numberOfInstances: 1
  resources:
    requests:
      cpu: 10m
    limits:
      cpu: 500m
      memory: 350Mi
  env:
  - name: pg_cluster_restart_attempt
    value: attempt-1

  # # Uncomment the next lines to create a standby cluster from the S3
  # # backup. Change the path accordingly. Once the standby cluster has
  # # been sycnronized, comment the lines again to detach the standby
  # # cluster from the primary cluster.
  # standby:
  #   s3_wal_path: "s3://swpt/spilo/accounts-db-01/wal/17"
