apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: "-101"

commonLabels:
  app.kubernetes.io/instance: shard-101

configMapGenerator:
  - name: configuration
    literals:
      # Must be either an empty string, or a string of 0s or 1s. "101" for
      # example.
      - "shard_suffix="

      # The value of `PROTOCOL_BROKER_QUEUE_ROUTING_KEY` must correspond
      # to the `shard_suffix` value. For example, if `shard_suffix` is
      # "101", this value must be "1.0.1.#".
      - "PROTOCOL_BROKER_QUEUE_ROUTING_KEY=#"

      - "PROTOCOL_BROKER_PROCESSES=1"
      - "PROTOCOL_BROKER_THREADS=3"
      - "PROTOCOL_BROKER_PREFETCH_COUNT=10"

      - "CHORES_BROKER_PROCESSES=1"
      - "CHORES_BROKER_THREADS=3"
      - "CHORES_BROKER_PREFETCH_COUNT=10"

      - "WEBSERVER_PROCESSES=1"
      - "WEBSERVER_THREADS=3"
      - "WEBSERVER_PORT=8080"

      - "FLUSH_PROCESSES=1"
      - "FLUSH_PERIOD=1.5"

      - "DELETE_PARENT_SHARD_RECORDS=false"
      - "FETCH_API_URL=http://accounts-cache.swpt-accounts.svc:80"

      - "APP_LOG_LEVEL=warning"
      - "APP_LOG_FORMAT=json"

resources:
  - postgres-cluster.yaml
  - main.yaml
