apiVersion: "acid.zalan.do/v1"
kind: OperatorConfiguration
metadata:
  name: postgresql-operator-default-configuration
configuration:
  dockerImage: ghcr.io/swaptacular/spilo-17@sha256:23861da069941ff5345e6a97455e60a63fc2f16c97857da8f85560370726cbe7
  max_instances: 7
  set_memory_request_to_limit: false
  kubernetes:
    enable_finalizers: false
    enable_owner_references: true
    enable_persistent_volume_claim_deletion: false
    watched_namespace: "*"
    enable_pod_antiaffinity: true
    pod_antiaffinity_topology_key: kubernetes.io/hostname
    pdb_master_label_selector: false
    pod_environment_configmap: "postgres-operator/spilo-env-config"
    pod_environment_secret: "spilo-env-secret"
    pod_service_account_name: postgres-pod
    pod_service_account_definition: '
      {
        "apiVersion": "v1",
        "kind": "ServiceAccount",
        "metadata": {
          "name": "postgres-pod"
        },
        "imagePullSecrets": [
          {
            "name": "regcreds"
          }
        ]
      }'
    inherited_labels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - app.kubernetes.io/component
    - app.kubernetes.io/part-of
  postgres_pod_resources:
    default_cpu_limit: "1"
    default_cpu_request: 100m
    default_memory_limit: 350Mi
    default_memory_request: 350Mi
  patroni:
    enable_patroni_failsafe_mode: true
  debug:
    debug_logging: false
