apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: swpt-accounts-peers
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/dev/swpt-accounts/node-data/peers
  prune: true
  timeout: 5m0s
  targetNamespace: swpt-accounts
