apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rabbitmq-system
  name: rabbitmq-cluster-operator
spec:
  strategy:
    type: "Recreate"
  template:
    spec:
      priorityClassName: critical-operator
      imagePullSecrets:
        - name: regcreds
      containers:
        - name: operator
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
