apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: test-cluster
  namespace: default
spec:
  teamId: "swpt"
  numberOfInstances: 2
  users:
    test_owner: []
  databases:
    test: test_owner
  patroni:
    synchronous_mode: true
  resources:
    requests:
      cpu: 50m
    limits:
      cpu: 500m
      memory: 500Mi
  volume:
    size: 1Gi
  additionalVolumes:
    - name: minio-ca-certificate
      mountPath: /certs/minio
      targetContainers: []
      volumeSource:
        configMap:
          name: kube-root-ca.crt
  # env:
  #   - name: WALG_S3_CA_CERT_FILE
  #     value: "/certs/minio/ca.crt"
