apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: test-cluster
  namespace: default
spec:
  teamId: "swpt"
  numberOfInstances: 2
  postgresql:
    version: "17"
  users:
    test_owner: []
  databases:
    test: test_owner
  patroni:
    synchronous_mode: true
  resources:
    requests:
      cpu: 10m
    limits:
      cpu: 500m
      memory: 350Mi
  volume:
    size: 1Gi
  additionalVolumes:
    - name: minio-ca-certificate
      mountPath: /certs/minio
      targetContainers: []
      volumeSource:
        configMap:
          name: kube-root-ca.crt
  # clone:
  #   cluster: "test-cluster"  # the same as the name of this cluster!
  #   timestamp: "2199-01-01T00:00:00.000+00:00"  # far away in the future
  # env:
  #   - name: WALG_S3_CA_CERT_FILE
  #     value: "/certs/minio/ca.crt"
