apiVersion: "acid.zalan.do/v1"
kind: OperatorConfiguration
metadata:
  name: postgresql-operator-default-configuration
  namespace: postgres-operator
configuration:
  docker_image: ghcr.io/zalando/spilo-17:4.0-p2
  max_instances: 3
  set_memory_request_to_limit: true
  kubernetes:
    enable_finalizers: false
    enable_owner_references: true
    enable_persistent_volume_claim_deletion: false
    watched_namespace: "*"
    pod_environment_configmap: "postgres-operator/spilo-custom-config"
    pod_environment_secret: "spilo-custom-secret"
    enable_pod_disruption_budget: false
  postgres_pod_resources:
    default_cpu_limit: "1"
    default_cpu_request: 100m
    default_memory_limit: 150Mi
    default_memory_request: 150Mi
  patroni:
    enable_patroni_failsafe_mode: true
