apiVersion: v1
kind: ConfigMap
metadata:
  name: spilo-custom-config
  namespace: postgres-operator
data:
  BACKUP_SCHEDULE: '00 01 * * *'
  BACKUP_NUM_TO_RETAIN: "5"
  WAL_S3_BUCKET: swpt
  WAL_BUCKET_SCOPE_PREFIX: ""
  WAL_BUCKET_SCOPE_SUFFIX: ""
  USE_WALG_BACKUP: "true"
  USE_WALG_RESTORE: "true"
  AWS_ACCESS_KEY_ID: console
  AWS_SECRET_ACCESS_KEY: console123
  AWS_S3_FORCE_PATH_STYLE: "true" # needed for MinIO
  AWS_ENDPOINT: "https://minio.minio-tenant.svc.cluster.local:443" # Endpoint URL to your S3 Endpoint; MinIO in this example
  AWS_REGION: us-east-1
  WALG_DISABLE_S3_SSE: "true"
  WALG_S3_CA_CERT_FILE: "/certs/minio/ca.crt" # needed for MinIO
  CLONE_METHOD: CLONE_WITH_WALE
  CLONE_WAL_S3_BUCKET: swpt
  CLONE_WAL_BUCKET_SCOPE_PREFIX: ""
  CLONE_WAL_BUCKET_SCOPE_SUFFIX: ""
  CLONE_USE_WALG_BACKUP: "true"
  CLONE_USE_WALG_RESTORE: "true"
  CLONE_AWS_ACCESS_KEY_ID: console
  CLONE_AWS_SECRET_ACCESS_KEY: console123
  CLONE_AWS_S3_FORCE_PATH_STYLE: "true"
  CLONE_AWS_ENDPOINT: "https://minio.minio-tenant.svc.cluster.local:443"
  CLONE_AWS_REGION: us-east-1
  STANDBY_WITH_WALE: "true"
  STANDBY_WALE_ENV_DIR: "/run/etc/wal-e.d/env-standby"
  STANDBY_WAL_S3_BUCKET: swpt
  STANDBY_WAL_BUCKET_SCOPE_PREFIX: ""
  STANDBY_WAL_BUCKET_SCOPE_SUFFIX: ""
  STANDBY_USE_WALG_BACKUP: "true"
  STANDBY_USE_WALG_RESTORE: "true"
  STANDBY_AWS_ACCESS_KEY_ID: console
  STANDBY_AWS_SECRET_ACCESS_KEY: console123
  STANDBY_AWS_S3_FORCE_PATH_STYLE: "true"
  STANDBY_AWS_ENDPOINT: "https://minio.minio-tenant.svc.cluster.local:443"
  STANDBY_AWS_REGION: us-east-1
