apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: standby-cluster
  namespace: default
spec:
  teamId: "swpt"
  numberOfInstances: 2
  postgresql:
    version: "17"
  users:
    test_owner: []
  databases:
    test: test_owner
  patroni:
    synchronous_mode: true
  resources:
    requests:
      cpu: 10m
    limits:
      cpu: 500m
      memory: 350Mi
  volume:
    size: 1Gi
  additionalVolumes:
    - name: minio-ca-certificate
      mountPath: /certs/minio
      targetContainers: []
      volumeSource:
        configMap:
          name: kube-root-ca.crt
  standby:
    s3_wal_path: "s3://swpt/spilo/test-cluster/wal/17"
  env:
    - name: STANDBY_WITH_WALE
      value: "true"
    - name: STANDBY_WALE_ENV_DIR
      value: "/run/etc/wal-e.d/env-standby"
    - name: STANDBY_WAL_S3_BUCKET
      value: swpt
    - name: STANDBY_WAL_BUCKET_SCOPE_PREFIX
      value: ""
    - name: STANDBY_WAL_BUCKET_SCOPE_SUFFIX
      value: ""
    - name: STANDBY_USE_WALG_BACKUP
      value: "true"
    - name: STANDBY_USE_WALG_RESTORE
      value: "true"
    - name: STANDBY_AWS_ACCESS_KEY_ID
      value: console
    - name: STANDBY_AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: spilo-custom-secret
          key: AWS_SECRET_ACCESS_KEY
    - name: STANDBY_AWS_S3_FORCE_PATH_STYLE
      value: "true"
    - name: STANDBY_AWS_ENDPOINT
      value: "https://minio.minio-tenant.svc.cluster.local:443"
    - name: STANDBY_AWS_REGION
      value: us-east-1
    - name: STANDBY_WALG_DISABLE_S3_SSE
      value: "true"
    - name: STANDBY_WALG_S3_CA_CERT_FILE
      value: "/certs/minio/ca.crt"
