apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# You may edit this section to specify different OCI images to use for
# the controllers. Also, it is recommended to specify an image digest
# instead of an image tag ("digest: <DIGEST>", instead of "newTag:
# <TAG>").
#
images:

# Cert-manager:
- name: quay.io/jetstack/cert-manager-cainjector:v1.17.4
  newName: ghcr.io/swaptacular/cert-manager-cainjector
  digest: sha256:0f7dcc7ca23dc95c32323ddd7b638c3fa318662985378360a1aeb9c72473e147
- name: quay.io/jetstack/cert-manager-controller:v1.17.4
  newName: ghcr.io/swaptacular/cert-manager-controller
  digest: sha256:189920e5752ec7d56a6329347969d847bfd867c07119873c849f300795a0be7b
- name: quay.io/jetstack/cert-manager-webhook:v1.17.4
  newName: ghcr.io/swaptacular/cert-manager-webhook
  digest: sha256:1e4711c91ea4c45baab763bec3875528847f8221a577aa81b325cac49d68cd09

patches:

# This patch configures the Cert-manager's controller pod.
#
- patch: |-
    # Configures the OCI image used for performing an ACME "http01"
    # challenge. This simply replaces one of the passed parameters
    # when launching the Cert-manager's controller.
    - op: replace
      path: /spec/template/spec/containers/0/args/3
      value: --acme-http01-solver-image=ghcr.io/swaptacular/cert-manager-acmesolver@sha256:d1c5cc961ba68c341c482554a9e0f3b776394216b2150adf8b5328379c72dc3e

    # Configures CPU and memory requests and limits for the
    # Cert-manager's controller pod.
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 1m
          memory: 30Mi
        limits:
          cpu: 100m
          memory: 500Mi

  target:
    kind: Deployment
    name: cert-manager
    namespace: cert-manager

# This patch configures the CPU and memory requests and limits for the
# Cert-manager's cainjector pod.
#
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 1m
          memory: 39Mi
        limits:
          cpu: 100m
          memory: 500Mi

  target:
    kind: Deployment
    name: cert-manager-cainjector
    namespace: cert-manager

# This patch configures the CPU and memory requests and limits for the
# Cert-manager's webhook pod.
#
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 1m
          memory: 20Mi
        limits:
          cpu: 100m
          memory: 500Mi

  target:
    kind: Deployment
    name: cert-manager-webhook
    namespace: cert-manager

secretGenerator:
- name: regcreds
  namespace: cert-manager
  files:
  - ".dockerconfigjson=../regcreds.json.encrypted"
  options:
    disableNameSuffixHash: true
  type: kubernetes.io/dockerconfigjson

resources:
- ../../base/cert-manager/
