apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

secretGenerator:
- name: loki-object-store
  literals:
  - AWS_ENDPOINT=https://minio:443
  - AWS_REGION=us-east-1
  - AWS_ACCESS_KEY_ID=console
  - AWS_SECRET_ACCESS_KEY=console123
  options:
    disableNameSuffixHash: true
  type: Opaque

resources:
- namespace.yaml
- kube-prometheus-stack.yaml
- promtail.yaml
- loki.yaml
- loki-pdb.yaml
- network-policies.yaml
- kubernetes-event-exporter.yaml
