apiVersion: v1
kind: Service
metadata:
  name: mailhog
  namespace: mailhog
spec:
  selector:
    app: mailhog
  ports:
    - name: smtp
      port: 1025
    - name: http
      port: 8025
  type: LoadBalancer
