apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: simple-git-server

configMapGenerator:
- name: sshd-config
  files:
    - sshd_config=static/sshd_config
    - trusted_user_ca_keys=trusted_user_ca_keys
- name: nginx-config
  files:
  - nginx.conf=static/nginx.conf
  - default.conf.template=static/default.conf.template

secretGenerator:
- name: host-keys
  files:
    - secret-files/ssh_host_rsa_key.pub
    - secret-files/ssh_host_rsa_key
  options:
    disableNameSuffixHash: true
- name: regcreds
  files:
    - ".dockerconfigjson=secret-files/regcreds.json"
  options:
    disableNameSuffixHash: true
  type: kubernetes.io/dockerconfigjson
- name: nginx-ssl-certificate
  files:
  - cert.pem=secret-files/cert.pem
  - key.pem=secret-files/key.pem
  options:
    disableNameSuffixHash: true
  type: Opaque

# You may edit the following lines to specify a different container
# image repository. Also, it is recommended to specify an image digest
# instead of an image tag.
images:
- name: docker.io/rockstorm/git-server:2.47
  newName: docker.io/rockstorm/git-server
  digest: sha256:0b2f02446b2e3824f1fe17b8ba57f7d732b8ad440f7c248f007e6fc38b5d8935
- name: nginx
  newName: docker.io/nginx
  digest: sha256:1eadbb07820339e8bbfed18c771691970baee292ec4ab2558f1453d26153e22d

resources:
  - manifests.yaml
