apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# The number of replicas for each component. One replica works fine,
# but to have high-availability, should be at least 2.
#
replicas:
- name: login-web-server
  count: 1

# OCI images to use for the different containers:
#
images:
- name: swpt-login
  newName: ghcr.io/swaptacular/swpt_login
  newTag: 0.15.0

secretGenerator:
- name: postgres.login-db.credentials.postgresql.acid.zalan.do
  files:
  - password=../secrets/postgres-cluster-password.encrypted
  literals:
  - username=postgres
  options:
    disableNameSuffixHash: true
    labels:
      app.kubernetes.io/name: swpt-debtors
      app.kubernetes.io/component: login-db
      application: spilo
      cluster-name: login-db
      team: swpt
  type: Opaque
- name: standby.login-db.credentials.postgresql.acid.zalan.do
  files:
  - password=../secrets/postgres-cluster-password.encrypted
  literals:
  - username=standby
  options:
    disableNameSuffixHash: true
    labels:
      app.kubernetes.io/name: swpt-debtors
      app.kubernetes.io/component: login-db
      application: spilo
      cluster-name: login-db
      team: swpt
  type: Opaque
- name: db-owner.login-db.credentials.postgresql.acid.zalan.do
  files:
  - password=../secrets/postgres-cluster-password.encrypted
  literals:
  - username=db_owner
  options:
    disableNameSuffixHash: true
    labels:
      app.kubernetes.io/name: swpt-debtors
      app.kubernetes.io/component: login-db
      application: spilo
      cluster-name: login-db
      team: swpt
  type: Opaque

resources:
- postgres-cluster.yaml
- dragonfly-db.yaml
- mailhog.yaml
- ../../../base/swpt-debtors/swpt-login/

patches:
- path: ../../../base/swpt-debtors/swpt-login/patches/postgres-cluster.yaml
  target:
    group: acid.zalan.do
    kind: postgresql
    name: login-db
    version: v1

- path: ../../../base/swpt-debtors/swpt-login/patches/dragonfly-db.yaml
  target:
    group: dragonflydb.io
    kind: Dragonfly
    name: dragonfly-db
    version: v1alpha1
