apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: login-db  # must be "login-db"
spec:
  # Specifies the "spilo" OCI image to use.
  #
  dockerImage: ghcr.io/zalando/spilo-17:4.0-p2

  # Specifies the disk space allocated for the database. The value
  # must not be decreased.
  #
  volume:
    size: 1Gi

  # Specifies Kubernetes memory and CPU requests and limits. It is
  # recommended that the memory request is the same as the memory
  # limit.
  #
  resources:
    requests:
      cpu: 10m
      memory: 350Mi
    limits:
      cpu: 500m
      memory: 350Mi

  # Specifies the number of PosgreSQL server instances in the cluster.
  # Must be between 1 and 3. It is recommended to be at least 2.
  #
  numberOfInstances: 1

  env:
  # You can change the value of this variable to trigger a restart of
  # the PosgreSQL cluster.
  #
  - name: pg_cluster_restart_attempt
    value: attempt-0

  # # Uncomment the these lines to recover from the S3 backup. Once the
  # # data has been recovered successfully, the lines can be commented
  # # again.
  # clone:
  #   cluster: login-db
  #   timestamp: "2199-01-01T00:00:00.000+00:00"

  teamId: swpt
  postgresql:
    version: "17"
  users:
    db_owner: []
  databases:
    db: db_owner
