apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- network-policies.yaml
- solver.yaml
- web-server.yaml
- swagger-ui.yaml
- internal-broker-pdb.yaml
- internal-broker-policies.yaml
