apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: isolate-trade-solver-db
  labels:
    app.kubernetes.io/name: swpt-trade
    app.kubernetes.io/component: solver-db
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: swpt-trade
      app.kubernetes.io/component: solver-db
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: swpt-trade
          app.kubernetes.io/component: solver-db
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: postgres-operator

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-trade-solver-db-users
  labels:
    app.kubernetes.io/name: swpt-trade
    app.kubernetes.io/component: solver-db
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: swpt-trade
      app.kubernetes.io/component: solver-db
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - port: 5432
    from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: swpt-trade
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: swpt-trade-worker
          app.kubernetes.io/part-of: swpt-trade

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-http-fetcher-access
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: http-fetcher
      app.kubernetes.io/name: swpt-trade-worker
      app.kubernetes.io/part-of: swpt-trade
  policyTypes:
  - Egress
  egress:
  - {}
