source:
  group: acid.zalan.do
  version: v1
  kind: postgresql
  name: trade-worker-db
  fieldPath: metadata.name
targets:
  - select:
      name: trade-workerconfig
      kind: ConfigMap
    fieldPaths:
      - data.pg_cluster_name
    options:
      create: True
